### ISSUE TITLE
Hide/Un-hide input sources??

### ISSUE THREAD

**Issue by n0rt0nthec4t** [ol-iver/denonavr#104]
Is anyone aware of a way to high/unhide the input sources programmatically (Possibly via the /goform/AppCommand.xml) interface?

You can use this to determine "hidden" sources by the GetDeletedSource command, so just wounding if there is something like "SetDeletedSource"

Thanks

**Comment by n0rt0nthec4t** [comment]
OK, so doing some packet capture to/from my X3300W, there is a command.. This below was enabling Blu-ray via teh iPhone App

> <tx>
>   <cmd id="3">
>     <name>SetHideSources</name>
>     <list>
>       <param name="Blu-ray">1</param>
>     </list>
>   </cmd>
> </tx>

**Comment by JPHutchins** [comment]
What would the full command be?  The only ones I have seen like that are XML of a format like this:
```
<?xml version="1.0" encoding="utf-8"?>
<tx>
  <cmd id="1">SetDialogLevel</cmd>
  <value>17</value>
</tx>
```
or
```
<?xml version="1.0" encoding="utf-8"?>
<tx>
  <cmd id="3">
    <name>SetSourceRename</name>
    <list>
      <param name="DVD">Test</param>
    </list>
  </cmd>
</tx>
````

**Comment by n0rt0nthec4t** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<tx>
	<cmd id="3"> <name>SetHideSources</name>
		<list>
			<param name="Blu-ray">1</param>
		</list>
	</cmd> 
</tx>
```

Where the param name is the input name and 0 to hide input or 1 to show input

entry point is /goform/AppCommand0300.xml

**Comment by JPHutchins** [comment]
Awesome!  I have a fork here where I started working on the XML commands.  

https://github.com/JPHutchins/denonavr/blob/xml-commands/denonavr/helpers.py

https://github.com/JPHutchins/denonavr/blob/xml-commands/denonavr/commands.py

I realized afterwards that it would be nice to have access to the commands with different param names so the XmlCommand and XmlCommand3 classes would need to be modified to allow for this.

**Comment by n0rt0nthec4t** [comment]
I';m actually also trying to find a command to get the firmware version of the AMP. Found some other commands such as "GetNetworkInfo" and "getUpdateDetails" but the latter doesn't seem todo anything

```
<?xml version="1.0" encoding="utf-8"?>
<tx>
  <cmd id="3">
    <name>GetNetworkInfo</name>
    <list>
      <param name="connection"></param>
      <param name="ssid"></param>
      <param name="dhcp"></param>
      <param name="ipaddr"></param>
      <param name="macaddr"></param>
    </list>
  </cmd>
</tx>
````

**Comment by JPHutchins** [comment]
Closest I got in my data dump was something like "SetFirmware" so maybe try "GetFirmware".  Either way it may or may not be part of the API and if it is it should show up in your wireshark.

https://github.com/JPHutchins/denonavr/blob/xml-commands/doc/XML_data_dump.txt

**Comment by n0rt0nthec4t** [comment]
New command

```<?xml version="1.0" encoding="utf-8"?>
<tx> 
  <cmd id="1">GetTunerStatus</cmd>
</tx>

Outputs:
<rx>
  <cmd>
    <band>FM</band>
    <frequency>101.50</frequency>
    <automanual>AUTO</automanual>
    <name>triple j
</name>
    <presetno>OFF</presetno>
    <presetname/>
  </cmd>
</rx>
