### ISSUE TITLE
Not able to match sound mode: 'Dolby Audio - Dolby Digital Plus', returning raw sound mode.

### ISSUE THREAD

**Issue by WhimsySpoon** [ol-iver/denonavr#105]
Log Warning shown on startup:

`Not able to match sound mode: 'Dolby Audio - Dolby Digital Plus', returning raw sound mode.`

**Comment by starkillerOG** [comment]
@WhimsySpoon I included the reported sound mode in the PR that I just refrenced.
If that gets merged it will fix this warning.

**Comment by WhimsySpoon** [comment]
Excellent, thanks @starkillerOG

**Comment by ol-iver** [comment]
Added the changes to the library and home-assistant https://github.com/home-assistant/home-assistant/pull/30421
