### ISSUE TITLE
List all available command

### ISSUE THREAD

**Issue by ghost** [ol-iver/denonavr#110]
Hi
I have a model Denon AVR-X2100W
Where i can found all list command by URL http for this model ? I try add to my Home Assistant button with command to play Favorite station.... And i dont know how....?

**Comment by JPHutchins** [comment]
A big command list is here:
https://github.com/JPHutchins/denonavr/blob/3313-IR/denonavr/ir_code.py

And implementation of generic IR commands from that list looks like:
```python
def send_post_ir(self, command):
        """Send IR command via HTTP post to receiver."""
        res = requests.post("http://{host}:{port}{uri}{command}".format(
            host=self._host, port=self._receiver_port, uri=IPHONE_APP_DIRECT,
            command=command), timeout=self.timeout)
        if not res.status_code == 200:
            _LOGGER.error((
                "Host %s returned HTTP status code %s to POST command at "
                "end point %s"), self._host, res.status_code, command)
            return False
        return True
```

From Home Assistant of course you can just POST to the API endpoint or send telnet command.

**Comment by ghost** [comment]
But how play from home assistant Favorite station? What command use?

**Comment by JPHutchins** [comment]
POST to this endpoint.  I am sorry I am forgetting right now whether or not you need the port number, try with and without!
`/goform/formiPhoneAppDirect.xml?RCKSK0410242`

**Comment by ghost** [comment]
But on Favorite station internet radio i have more than 4 station....

**Comment by ghost** [comment]
I Type in webbrowser this and no working
http://ADDRESS_IP/goform/formiPhoneAppDirect.xml?RCKSK0410242

**Comment by ghost** [comment]
Other works ok. But still i dont know how play station Favorite from network.... Command
http://IP/goform/formiPhoneAppDirect.xml?RCKSK0410741

Play network station latest run.
