### ISSUE TITLE
How to add denonavr in home assistant

### ISSUE THREAD

**Issue by advead** [ol-iver/denonavr#112]
Hello,

I have tried the script in python and its working for my X2400 avr.
Can somebody tells my how I must put this in my home assistant so I can use it via the interface of home assistant ? I am not very experienced to do this.

regards

**Comment by ol-iver** [comment]
You can find examples of home-assistant configuration in its help files
https://www.home-assistant.io/integrations/denonavr/

**Comment by ghost** [comment]
Hi.  But is any chance to generate URL link to run play Favorite station - internet radio?
