### ISSUE TITLE
Not able to match sound mode: 

### ISSUE THREAD

**Issue by idfxken** [ol-iver/denonavr#113]
Just some nitpicking, but I tried to find all not yet added modes at once.
On a X3500H the following sound modes are not yet added or correctly named:
```
Not able to match sound mode: 'Dolby Audio - DD+   + Neural:X', returning raw sound mode.
Not able to match sound mode: 'Dolby Audio - DD+   + DSur', returning raw sound mode.
Not able to match sound mode: 'DTS + Virtual:X', returning raw sound mode.
Not able to match sound mode: 'Dolby Audio - Dolby Digital Plus', returning raw sound mode.
Not able to match sound mode: 'Dolby Audio - TrueHD + DSur', returning raw sound mode.
Not able to match sound mode: 'Dolby Audio - Dolby TrueHD', returning raw sound mode.
Not able to match sound mode: 'Dolby Audio - TrueHD + Neural:X', returning raw sound mode.
Not able to match sound mode: 'DTS-HD + Neural:X', returning raw sound mode.
```

In the same format, 'DTS + Neural:X' gets reformed to DTS surround.
'DTS-HD' is not throwing an error but sound mode is empty.
Could run debug logs in a few days, if you want.

There are some more with DTS master and atmos,
but can't get them as my shield refuses to play with DTS Master or atmos atm....

**Comment by ol-iver** [comment]
bumped to new version in homeassitant too
https://github.com/home-assistant/home-assistant/pull/31629
