### ISSUE TITLE
Denon integration not showing up

### ISSUE THREAD

**Issue by 4lphac** [ol-iver/denonavr#126]
I've enabled media_player as directed in the manual page, but I couldn't make the device appear on home assistant, from the logs everything looks fine, denonavr is loaded and it can even find my media player ip, but it won't show up. 

configuration.yaml:
shelly:
media_player:
  - platform: denonavr
    host: 192...
    name: Denon
discovery:
binary_sensor:

I've also tried enabling autodiscovery and it works, but it won't show up either

**Comment by starkillerOG** [comment]
What do you mean with "won't show up"?
Is it listed under states in the dev tools of homeassistant as a device?

If you mean it is not showing up in the frontend you just need to add a media_player card to the frontend

**Comment by starkillerOG** [comment]
Why does your config include "discovery" and "binary_sensor" under the denonavr platform?
Those are not properties of denonavr
