### ISSUE TITLE
Since version 107 everytime WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform denonavr is taking over 10 seconds.

### ISSUE THREAD

**Issue by ghost** [ol-iver/denonavr#130]
Hi, 
I wanted to let you know that the Denon integration seems to have trouble since version 107.x

The response of the Denon AVR is bad. Won't react at all sometimes. There are more errors than the one below. I'll collect them. 

2020-04-10 10:12:44 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform denonavr is taking over 10 seconds.

All other devices in the network seem not to have trouble reaching the reciever. And rebooting updating (running 108.2 now) on the Pi4b won't solve it.

Is this a new known issue or am I the only one having this?
Thanks for reading.

Configyaml

media_player:
  - platform: denonavr
    host: 192.168.49.7
    name: Denon DN-500AV
    show_all_sources: false
    timeout: 2

**Comment by ghost** [comment]
2020-04-12 12:03:42 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform denonavr is taking over 10 seconds.
2020-04-12 12:03:43 WARNING (SyncWorker_15) [DenonAVR] Not able to match sound mode: 'DOLBY PL2 music', returning raw sound mode.

**Comment by ghost** [comment]
There is lag in the response of the Denon ingegration. But it in essence works. So I'm closing my own issue, to spare your time. It's gonna take more time go gather the errors i've seen before. It's so random. I'll open it again if everything would go haywire one day. Let's hope not.
My case feels weak. So i'm closing it.

**Comment by ghost** [comment]
The issue arrise when you stream airplay to the Denon device.

**Comment by starkillerOG** [comment]
> 
> 
> 2020-04-12 12:03:42 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform denonavr is taking over 10 seconds.
> 2020-04-12 12:03:43 WARNING (SyncWorker_15) [DenonAVR] Not able to match sound mode: 'DOLBY PL2 music', returning raw sound mode.

@YRRK I just noticed the warning about the sound mode in your log, I just fixed that one in this PR: https://github.com/scarface-4711/denonavr/pull/134

**Comment by starkillerOG** [comment]
The warning about the 10 seconds is just because HomeAssistant is beeing a bit slow.
However we are almost switching to Config Flow for loading the Denonavr Platform and that does some things diffrently, schould be faster since its uses asyncio for I/O during setup.

I would wait untill the Config Flow is implemented, I think the warning will then go away.

Anyway it is nothing to be conserend about, it just takes a bit long for your receiver to respond during intial setup.

**Comment by ghost** [comment]
Thanks!
