### ISSUE TITLE
Integration isn't working until HA core is manually restarted

### ISSUE THREAD

**Issue by daha76** [ol-iver/denonavr#133]
Hello,

since several last versions of Hassio I have tu manually restart HA Core to get danonavr up and running. then it will run until I turn turn off my receiver completely. I mean I disconnect it from the main power supply with smart plug. Not only this device is disconnected also TV, TV Box, BD player, set top box, ... but only my Marantz NR1609 has problem to become available when all devices are connected back to the mains. Interestingly default Hassio media player will find my receiver and I can start internet playing radio or Spotify but that is all.  Once I restarted HA with command: **ha core restart**, receiver is recognised and will work as expected. Before HA Core restart I can see ERRORs in the log like :

ERROR (SyncWorker_6) [DenonAVR] Host 192.168.1.4 returned HTTP status code 403 to POST command at end point /goform/AppCommand.xml
ERROR (SyncWorker_6) [DenonAVR] End point /goform/AppCommand.xml on host 192.168.1.4 returned malformed XML.

It behaves like when it was not  properly identified.

Any idea why this happening? Looks like identification of the receiver type is made only at startup. When device disappear, because it is disconnected from network or completely turned off, it wouldn't be properly identified again when it is back on.

**Comment by ol-iver** [comment]
I tried to improve resilience when devices are offline in the latest patch. Please check again when there is a new version of hassio which includes this pull request https://github.com/home-assistant/core/pull/35255
If you still facing your problem then, please reopen this issue.

**Comment by daha76** [comment]
Hi,

Actually I run HASSIO 0.111.4 and the problem is still there. When device comes online it wouldn't work in HA and only way to get it up and running is restarting the HA.
