### ISSUE TITLE
Not able to match sound mode: 'Dolby Digital + + Neural:X', returning raw sound mode.

### ISSUE THREAD

**Issue by lpuzzello** [ol-iver/denonavr#135]
I'm receiving "Not able to match sound mode: 'Dolby Digital + + Neural:X', returning raw sound mode." in Developer Logs of Home Assistant.

Using the component from Home Assistant 0.109.6 docker image.

**Comment by starkillerOG** [comment]
This error schould not be possible, 'Dolby Digital + + Neural:X' is already in the matching dictinary since denonavr version 0.7.7

Are you using a custom integration that uses the deononavr library?
Which version of denonavr are you running?

**Comment by lpuzzello** [comment]
Yes. It's weird because was working in a previous release of HA. 
I'm using the integration is delivered with the Docker Image. 
https://www.home-assistant.io/integrations/denonavr/
Maybe it's broken on this update.
