### ISSUE TITLE
Unable to identify Marantz SR5014

### ISSUE THREAD

**Issue by mazstars** [ol-iver/denonavr#141]
Hi,

Recently I replaced my old Denon receiver with Marantz SR5014, and found it couldn't be identified by homeassistant.
I checked the code and obviously the pattern does not match the new types of Marantz receivers.

DEVICEINFO_AVR_X_PATTERN = re.compile(
    r"(.*AV(C|R)-(X|S).*|.*SR500[6-9]|.*SR60(07|08|09|10|11|12|13)|."
    r"*SR70(07|08|09|10|11|12|13)|.*NR1604|.*NR1710)")

I manually modified the pattern to SR50(0|1)[0-9] and worked, so maybe it is better to rework the Marantz pattern a little bit to loose the constraint.

Dennis

**Comment by starkillerOG** [comment]
Sounds good, could you make a pull request to modify the SR50 series matching?

**Comment by ol-iver** [comment]
I just added it in the latest version.
