### ISSUE TITLE
Denon 1500H shows idle when switched on via remote control.

### ISSUE THREAD

**Issue by caddyblack** [ol-iver/denonavr#146]
I use home assistant to read the status of my denon 1500H receiver.
The information I get is correct if I use the HEOS app, spotify or another network based application.
If I switch on the receiver with the remote control the status does not change from idle to playing as it does when using an app.
The volume setting is received though, even when changed via remote controller.
Is this a bug in the software or am I using the denon integration in the wrong way?

**Comment by starkillerOG** [comment]
@caddyblack not sure why the power status does not sync, it schould.
However note that it can take a while before HomeAssistant sees the power change, the polling intervall is I think 10 seconds.
So i think it could take up to 10 seconds for HomeAssistant to notice a change...

**Comment by caddyblack** [comment]
The denonavr integration is perfect for status. Off an on are registered immediately. My HEOS GO speakers are not supported by this integration. For that I installed HEOS integration. That integration does support both devices. Only the HEOS integration does not detect the on / off of my 1500 receiver. Bottomline I have both integrations and use parts of both.
