### ISSUE TITLE
Denon AVR 3100W

### ISSUE THREAD

**Issue by cbuechel** [ol-iver/denonavr#148]
I had the Denon AVR 3100W working with the integration up until this morning. When I go to enter the IP address, I get 

`Missing receiver information: manufacturer 'None', name 'Denon AVR-X3100W', model 'None', type 'avr-x'`

Have not made any software updates and rebooted HA. Still no luck

**Comment by starkillerOG** [comment]
You need to power cycle the receiver, disconnect it from mains, wait 10 sec and reconnect it.
The error message in HomeAssistant schould actually state this (at least in english, do not know if it made it to all the translations).

**Comment by starkillerOG** [comment]
@cbuechel is the issue resolved?
If so, please close this issue.
