### ISSUE TITLE
Sound mode 7.1

### ISSUE THREAD

**Issue by bartt-cz** [ol-iver/denonavr#149]
As instructed in notes ... there is one unrecognized sound mode (on Marantz SR-7010):

`Not able to match sound mode: 'MULTI CH IN 7.1', returning raw sound mode.`

And of course - thank you very much for your perfect work on this library!

**Comment by starkillerOG** [comment]
@bartt-cz I just added it in this PR: https://github.com/scarface-4711/denonavr/pull/147
Thanks for reporting!
