### ISSUE TITLE
Change channel levels

### ISSUE THREAD

**Issue by hvanoch** [ol-iver/denonavr#152]
Would it be possible to read and change the channel level?

I have a Marantz SR6010 and would love to be able to remote change the subwoofer level.
I know I can do a post to `/OPTION/CHANNELLEVELADJUST/s_option.asp`

Would be cool If I could then automate this through home assistant. (If our child is to sleep lower the subwoofer level automaticly)

Would you be interested in a PR for this?

**Comment by starkillerOG** [comment]
check out this PR: https://github.com/scarface-4711/denonavr/pull/144
I think someone is already working on this.
However I do not know what the current state on that PR is...

**Comment by MarBra** [comment]
the PR #144 is ready for review. Feel free to give it a try with your model :smile:

**Comment by hvanoch** [comment]
I don't think that is what I mean. #144 is about treble and base. I am talking about the channels. (front left, front right, rear, subwoofer level) 
This is how it look through the web interface of the marantz
![image](https://user-images.githubusercontent.com/6741991/94110492-0518d980-fe43-11ea-9ad9-f4cf182ef4cc.png)

**Comment by JPHutchins** [comment]
These sorts of commands looked like this on my Denon 1400.

```
Confirmed that -12dB = 0, 0dB = 24, +12dB = 48
Confirmed uses conventional names:
FL, FR, SL, SR, SW, C (probably RL and RR for 7.1)
Someone would need to check Atmos naming conventions
but manually setting Atmos channels isn't really desirable.
<?xml version="1.0" encoding="utf-8"?>
<tx>
  <cmd id="1">SetChLevel</cmd>
  <name>SR</name>
  <value>24</value>
</tx>
```
From my data dump here https://github.com/JPHutchins/denonavr/blob/d9797c6e629b963db3a0f760d16ade3e635070b2/doc/XML_data_dump.txt#L186-L196

And can be implemented like:
https://github.com/JPHutchins/denonavr/blob/master/denonavr/helpers.py

And:
https://github.com/JPHutchins/denonavr/blob/master/denonavr/commands.py

For example this will set LFE channel level
```python
SET_LFE_LEVEL = XmlCommand1(
    "Subwoofer Level", "SetChLevel", (0, 48), name="SW"
)
```
And can be called from the main program like:
```python
def set_lfe_level(self, value):
    """Set LFE Level via HTTP post command."""
    try:
        response = self.exec_xml_appcommand_post(SET_LFE_LEVEL, value)
    except requests.exceptions.RequestException:
        _LOGGER.error("Connection error: command not sent.")
        return response
```

It was going to be a ton of work to redo the entire command library using these XML formats so I abandoned it.  It is my hope to discover a means of "getting valid command lists" over SSDP to overcome generational differences in command formats.  It is noteworthy that Denon, and many brands, do often maintain backwards compatibility of IP commands even if it is not documented.

**Comment by JPHutchins** [comment]
Have you tried the denonavr.get_command service?  https://www.home-assistant.io/integrations/denonavr/#service-denonavrget_command?

I see that we are exposing denonavr.send_get_command() to the HA integration.  So accommodating more POST commands should be as simple as exposing denonavr.send_post_command() to HA.

First step would be to verify perhaps via Python repl that your command works as follows:

```
pip install denonavr
import denonavr
d = denonavr.DenonAVR("IP address as string")
d.send_post_command("/OPTION/CHANNELLEVELADJUST/s_option.asp", "I don't know what the body should be - try numbers between 0 and 48?")
```

https://github.com/scarface-4711/denonavr/blob/fa670e5daf8a7859b2b1eaff6f707d5100e7d2f8/denonavr/denonavr.py#L413-L424


By the way, I want the same automation as you but mostly to use the "set dynamic vol" or whatever it's called on different models.  It is the dynamic compression setting that used to be called "night mode".  Newer audio formats even have a metadata track that does the adjusting without relying on the traditional "dynamic compression algorithm" approach which is a heavy-handed approach.
