### ISSUE TITLE
comment typo in power_on 

### ISSUE THREAD

**Issue by brikrav** [ol-iver/denonavr#154]
def power_on(self):
This comment should be """Turn **on** receiver via HTTP get command."""

https://github.com/scarface-4711/denonavr/blob/fa670e5daf8a7859b2b1eaff6f707d5100e7d2f8/denonavr/denonavr.py#L1791

**Comment by starkillerOG** [comment]
Thanks for reporting!
fixed this in https://github.com/scarface-4711/denonavr/pull/147.

**Comment by starkillerOG** [comment]
@scarface-4711 this can be closed
