### ISSUE TITLE
Switching to NET/USB gives error

### ISSUE THREAD

**Issue by bwynants** [ol-iver/denonavr#155]
this is for a denon AVR3312

tracing shows 
[DenonAVR] Input function Internet Radio is not known

I use this via Home Assistant

NET/USB on denon is playing music via "internet radio"

**Comment by bwynants** [comment]
moved the 'internet radio' selection to the favorites under NET/USB now it says "Input function Favorites is not known"

**Comment by ol-iver** [comment]
@bwynants it took a while, but the issue should be solved with this [PR](https://github.com/home-assistant/core/pull/43370).

**Comment by ol-iver** [comment]
PR is merged
