### ISSUE TITLE
Not able to match sound mode: 'AURO-3D'

### ISSUE THREAD

**Issue by PeMaGonGo** [ol-iver/denonavr#159]
Hi, as mentioned in the title, I'm getting the following error.

Logger: DenonAVR
Source: /usr/local/lib/python3.8/site-packages/denonavr/denonavr.py:1716 

Not able to match sound mode: 'AURO-3D', returning raw sound mode

I have an AVR-X4500.

Tanks for the great work!

**Comment by ol-iver** [comment]
This error should be solved in the current version of Home Assistant.
There is a bug which prevents you from setting AURO-3D sound mode. Once [this PR](https://github.com/home-assistant/core/pull/43370) is merged, that issue should be solved too.

**Comment by ol-iver** [comment]
PR is merged
