### ISSUE TITLE
"Music" Auro-2D Surround kann nicht gesetzt werden

### ISSUE THREAD

**Issue by HookHM** [ol-iver/denonavr#161]
Hallo @scarface-4711 erstmal Danke für die tolle Arbeit.

Ich habe den DENON AVC-X4700H und kann über dein Addon nicht den Music Mode "Auro-2D Surround" Mode setzen. Woran kann das liegen?

Danke!

**Comment by ol-iver** [comment]
Hallo @HookHM 
Im Moment ist der Auro Sound Mode auf den falschen Namen gemapped. Der Fehler sollte mit diesem [Pull Request](https://github.com/home-assistant/core/pull/43370) behoben werden.

**Comment by HookHM** [comment]
Hallo @scarface-4711 danke für den fix. Was mir noch auffällt: Auf der Fernbedienung gibt es auf der "Direct" Taste bzw. bei der Option noch den Mode "Auto". Also "Direct", "Pure Direct" und "Auto" diesen kann ich hierüber auch nicht setzen.

**Comment by ol-iver** [comment]
Bei mir funktionieren Pure Direct sowie Auto ohne Probleme. Um dein Problem zu lösen, brauche ich mehr Informationen. Mach bitte dafür einen neuen Issue auf und schreibe ihn bitte auf Englisch, damit auch Leute mitlesen können, die kein deutsch verstehen.
Der PR für Auro 3D ist jetzt jedenfalls gemerged.

**Comment by LevelOne2k** [comment]
@scarface-4711 Unfortunately, Auro 2D does not work. The AVR can definitely do it. I also don't get the modes set via Telnet via „AURO-2D SURROUND“

**Comment by ol-iver** [comment]
The PR is merged but not in included into the current version of home assistant. Please wait for that.

**Comment by HookHM** [comment]
@scarface-4711 I understand. but the command „AURO-2D SURROUND“ doesn't seem to exist for the X4700H. The command seems to be different for activating Auro 2D.
