### ISSUE TITLE
Wie kann ich das hier installieren?

### ISSUE THREAD

**Issue by nubbel7404** [ol-iver/denonavr#162]
Guten Tag @scarface-4711 kannst du mir bitte erklären, wie ich dieses Plugin zum steuern eines Denon AVR installiere? Was genau ist pip? Ich habe einen RaspverryPi zur Verfügung. THX!

**Comment by ol-iver** [comment]
Hallo @nubbel7404 
pip ist der package manager von [python](https://www.python.org).
Wie du diese Bibliothek installierst und verwendest, ist ganz gut in der [README.md](https://github.com/scarface-4711/denonavr/blob/master/README.md) beschrieben

**Comment by ol-iver** [comment]
@nubbel7404 Du kannst auch [Home Assistant](https://www.home-assistant.io/) verwenden, da ist sie als [Integration](https://www.home-assistant.io/integrations/denonavr/) verfügbar.

**Comment by nubbel7404** [comment]
@scarface-4711 danke für den Verweis. Wird das neue Modell von 2020 4700 auch unterstützt?
