### ISSUE TITLE
Not able to match sound mode: 'MULTI IN + VIRTUAL:X', returning raw sound mode

### ISSUE THREAD

**Issue by superman3** [ol-iver/denonavr#165]
Not able to match sound mode: 'MULTI IN + VIRTUAL:X', returning raw sound mode in home assistant 0.117.6

**Comment by ol-iver** [comment]
Which sound mode is active, when this message appears?

**Comment by superman3** [comment]
Movie mode

**Comment by ol-iver** [comment]
Added with this commit https://github.com/scarface-4711/denonavr/commit/b073203039f1bf2a4b45cd48fd4e9ce298f1f34d
