### ISSUE TITLE
[DenonAVR] No mapping for source SERVER found

### ISSUE THREAD

**Issue by jaymansfield** [ol-iver/denonavr#190]
[DenonAVR] No mapping for source SERVER found

Received from trying to connect to Marantz NA7004

**Comment by ol-iver** [comment]
Could you please run [this script](https://github.com/scarface-4711/misc_python_tools/tree/master/denonavr) while your receiver is switched on and you selected the input function which causes this error?
It will generate some XML files with the responses of receiver. Please upload them here and I will have a look at it.
