### ISSUE TITLE
"Signal" vs "Mode" for sound value?

### ISSUE THREAD

**Issue by linerjoe** [ol-iver/denonavr#195]
Is it possible to get the same information presented by the AVR onscreen in the "Signal" field?

The Signal field can tell if it's actually an Atmos signal, or just TrueHD, etc. The Marantz/Denon apps don't show this level either (just the mode, such as direct), so I'm guessing it's not actually available?

TrueHD Atmos = DIRECT
TrueHD = DIRECT
Dolby Atmos - DD+ = DIRECT
PCM = Multi Ch In
DTS:X = DTS:X MSTR
All other DTS (DTS 5.1, DTS-HD MA) shows up as "DTS + Neural:X" on mine.
AAC/Stereo = STEREO

**Comment by starkillerOG** [comment]
@linerjoe you can look at the raw_sound_mode attribute in HomeAssistant (or directly in this library).
That returns directly the sound mode the receiver is reporting, I don't think more detailed info is available at the moment than the raw_sound_mode
