### ISSUE TITLE
Looking for details on the Denon REST API

### ISSUE THREAD

**Issue by petercarson** [ol-iver/denonavr#196]
Apologies, this is not an issue, but rather a request. I've just setup my new Denon NR1711 and I've got some custom home automation that I'd like to integrate it with. Looking for any details on the Denon REST API. I've browsed a few GitHub projects and this seems the most active currently.

I've got LAN access to the Denon setup. I tried hitting http://192.168.xxx.xxx/goform/formMainZone_MainZoneXml.xml to get the status, but I get a 403 access denied. It looks like most of the commands are POSTs, but I need enough to get started in Postman and start playing around. 

Any tips would be appreciated. Happy to formalize and publish once I get going.

Thanks,
Peter Carson

**Comment by JPHutchins** [comment]
It is likely that your API is at port 8080.  If you've already tried that
then try port 80.

**Comment by petercarson** [comment]
Thanks for the super-quick response. Just tried port 8080, and get the same result as port 80, 403. Do I need to authenticate and pass a token to the AVR before I can call this? Is the status call not a GET? I also tried at https://192.168.xxx.xxx:10443/goform/formMainZone_MainZoneXml.xml, which is the port for the settings menu, but that gives me The resource '/goform/formMainZone_MainZoneXml.xml' was not found.

Peter
________________________________

**Comment by JPHutchins** [comment]
If your receiver is newer it may not have the same status xml endpoint - it
may take some looking in the Python to find reference to other endpoints.

There is no auth and you can ignore 10443.

**Comment by ol-iver** [comment]
There is a [small script](https://github.com/scarface-4711/misc_python_tools/tree/master/denonavr) which queries most of the endpoints we are using to create test data.
You could run it for a quick check, if your receiver returns something meaningful.
