### ISSUE TITLE
Migrate away from async-lru

### ISSUE THREAD

**Issue by fabaff** [ol-iver/denonavr#203]
`async-lru` doesn't seems to be [maintained](https://github.com/aio-libs/async-lru/issues/315) anymore. 

Another project moved to `asyncstdlib`. This could be an option for `denonavr`.

**Comment by ol-iver** [comment]
good point and not very complicated 👍 
I moved to `asyncstdlib` in version [0.10.6](https://github.com/scarface-4711/denonavr/releases/tag/0.10.6) and include this version into home-assistant soon.
