### ISSUE TITLE
Denon AVR unavailable after update and cannot adding again.

### ISSUE THREAD

**Issue by Hatika78** [ol-iver/denonavr#206]
Hi,
I have been using this integration for a long time but since the update of home assistant 2021.5.0 and now 2021.5.1, it does not work anymore. I deleted the integration. On startup, my Denon AVR 2312 is found but if I try to add it, there is an error. I tried to add it manually with its IP address, same problem.
I can ping and connect to the web interface via this IP.
Downgrade to 2021.4.0 working well.
Do you think the update might have broken something?

**Comment by 8osman** [comment]
I've the same issue, not working anymore in 2021.05 or 2021.05.01 - I even went in and edited to allow the 0.10.07 and still no fix. Not finding receiver on network. By auto or manual IP.
Again I can open the receiver configuration via browser.

Edit - Also downgraded to 2021.4.4 and all working well again.

**Comment by Tommatheussen** [comment]
@Hatika78 it would be useful to post the error message you get ;) 
 It's possible the update broke something, sometimes these errors are very model dependent because some functionality is not fully supported for example.

**Comment by Hatika78** [comment]
@Tommatheussen I've tried to find the error message but after the update of Home Assistant to 2021.5.4 this morning, all is working well now. 
Thanks for your reply.
