### ISSUE TITLE
set_volume(volume) has no effect if volume is not a multiple of 0.5 [SR7007]

### ISSUE THREAD

**Issue by jonathangjertsen** [ol-iver/denonavr#209]
I can only get set_volume() to take effect when the volume is a multiple of 0.5. So set_volume(-35.5) works, but set_volume(-35.7) does not.

**Comment by ol-iver** [comment]
oh yes, the receivers seem to ignore other values. From the next version on volume will be rounded to a multiple of 0.5.

**Comment by prcutler** [comment]
Is this fixed in commit https://github.com/scarface-4711/denonavr/commit/f786dedf7a1ba3c4c2374a65737cf18721593c0c ?

If so - @jonathangjertsen can you test and update or close the issue?

Thanks!

**Comment by jonathangjertsen** [comment]
Looks like the right fix, thanks!
