### ISSUE TITLE
Marantz state shown as standby instead of off

### ISSUE THREAD

**Issue by bmesuere** [ol-iver/denonavr#210]
Since a recent Home Assistant update, the status of my Marantz receiver is shown as "standby" instead of "off" (it is in fact turned off). This has the unwanted side effect that toggle buttons to turn the receiver on/off stopped working because apparently "standby" is seen as "on" by Home Assistant.

Was this change intended behaviour?

**Comment by bukux** [comment]
I have same problem. My device is Marantz M-CR611 :-(

**Comment by bmesuere** [comment]
Since a more recent update, in addition to the annoying power state, the volume is consistently set to max. 

@scarface-4711 is there anything I can do to help with fixing this?

**Comment by ol-iver** [comment]
That was not intentional. The issue should be solved with my last commit. You could test it if you like.
I will include it into the next version.

**Comment by ol-iver** [comment]
I just created a [PR](https://github.com/home-assistant/core/pull/55805) in Home-Assistant for the changes. Please reopen if it is still not working after it is merged.
