### ISSUE TITLE
AVR-E300 Not Working After Latest Update

### ISSUE THREAD

**Issue by tholland15** [ol-iver/denonavr#214]
Updated HA and with that this plugin to latest version recently for a family member.

Since then HA has been unable to connect to their AVR-E300, breaking nearly everything they use HA for in their living room (all automations check the AVR status and input).

I've had them try the following:

1. Unplug both power and ethernet from the AVR for 60 seconds and plug back in. No change.
2. Delete integration in HA. After that, auto discovery finds the AVR, but trying to add the integration results in `ABORTED Failed to connect, please try again, disconnecting mains power and ethernet cables and reconnecting them may help`
3. After integration deletion, try adding the integration to HA manually via AVR IP Address results in `ABORTED Failed to connect, please try again, disconnecting mains power and ethernet cables and reconnecting them may help`

Unsure what to try now, I can access the AVR web controls going to the IP address via a browser and they work. The IP address is static. All of their home theater automations (about 25 separate ones) are all broken now after updating and I REALLY don't want to have to ask them to downgrade HA. 

Any advice?

**Comment by davidmonro** [comment]
I'm having what looks like the same problem with a Marantz NR1605, was working fine before I upgraded.

**Comment by tholland15** [comment]
Fixed after upgrading home assistant
