### ISSUE TITLE
Change input_func fail

### ISSUE THREAD

**Issue by JoCarBin** [ol-iver/denonavr#216]
Hi, sorry my english is very bad.
i have a error when i want change the function of the receiver.
Why?
Thanks.

------
discovered_denon.input_func = "CD"
Exception has occurred: AttributeError
can't set attribute
  File "/home/jcgarcia/Descargas/denon.X2000/denon.encender.MacSound.py", line 18, in <module>
    discovered_denon.input_func = "CD"

---------
My code:
import denonavr
import time

discovered_devices = denonavr.discover()
discovered_denon = denonavr.DenonAVR(discovered_devices[0]['host'])

discovered_denon.update() 
print(discovered_denon.name)

discovered_denon.power_on()
# time.sleep(5)
print("Encendiendo ...")

discovered_denon.input_func
print(discovered_denon.input_func_list)

discovered_denon.update()
discovered_denon.input_func = "CD"

**Comment by prcutler** [comment]
Hi, 

Replace the last line with:

`discovered_denon.set_input_func("CD")`

Also, move discovered_denon.update() from above it to the line below it:

```
discovered_denon.set_input_func("CD")
discovered_denon.update()

```

Hope that helps.

**Comment by JoCarBin** [comment]
Hello Paul,
Thank you very much for your help. I already have it working.

best regards

**Comment by prcutler** [comment]
Great!  If you can close the issue, that would be helpful.
