### ISSUE TITLE
Marantz NR1506 cannot select source anymore

### ISSUE THREAD

**Issue by hermannsblum** [ol-iver/denonavr#225]
Hi! 
After updating to the latest homeassistant version (I was before on something from early 2021) I cannot set the sources of my AVR anymore. In the logs, I see this error which seems related:

```
Logger: denonavr.ssdp
Source: /usr/local/lib/python3.9/site-packages/denonavr/ssdp.py:214
First occurred: 6:28:15 PM (1 occurrences)
Last logged: 6:28:15 PM

Error occurred during evaluation of SCPD XML from URI http://192.168.1.41:9080: not well-formed (invalid token): line 1, column 6
```

**Comment by ol-iver** [comment]
This is an [issue of home-assistant](https://github.com/home-assistant/core/issues/59189) and should be fixed in the next version.
