### ISSUE TITLE
Get Volume Changes / full method list

### ISSUE THREAD

**Issue by AKlemm88** [ol-iver/denonavr#229]
Hello, I want to display the current volume on a l2c display. Is it possible to get an information, if the volume has been changed by remote control?

Is there a complete list of available methods?

Thank you for the great work.

Best regards
Alex

**Comment by prcutler** [comment]
Hi Alex,

Yes, you can absolutely do this, I have a project that does this, but uses a physical rotary encoder instead of a remote.  I'm very much a novice at Python, so it's probably ugly code and I'm not doing it async yet, but here's my repo:  https://github.com/prcutler/pi-dial/ - there are two files, `pidial.py` to change the volume and `pidial-lcd.py` to display it on a 16x2 display.

**Comment by AKlemm88** [comment]
Wow, that Sounds nice. I want to have a look on your Code. I am a absolutely beginner in Python. But i think it is easy.

Thx
Alex

**Comment by AKlemm88** [comment]
I'm not sure about the "Volume Monitoring". How do you do this? I cant find anything in your Code for Monitoring the Volume.

I have a Problem, too. The data sent to the l2c Display is shown after a Delay of 2000ms. Do you know this?

Thx

**Comment by prcutler** [comment]
Yes, I know, I didn't like the flicker. 

To monitor the volume, you would need to write a method that continuously polls the receiver asking it for its volume.

If you have any questions about my code, feel free to start a discussion there unless your question is denonavr specific.  :)

--P

**Comment by AKlemm88** [comment]
At the Moment i dont have any questions for your Code. But it was very useful.

Maybe any other have an idea how to get the Info about the Volume or Input Changes?

At the moment my solution is not so nice.

while True:
   //getVolumeAndSomeOtherStuff
   time.sleep(0.05)

I hope it is possible to poll this information from receiver to my raspberry. A idea was, to get connected via telnet and push from the session, but that's not better I think.

Thank you
Alex
