### ISSUE TITLE
Not able to match sound mode: 'MULTI IN + DSUR', returning raw sound mode.

### ISSUE THREAD

**Issue by conductorj** [ol-iver/denonavr#230]
Logger: denonavr.soundmode
Source: /usr/local/lib/python3.9/site-packages/denonavr/soundmode.py:162 
First occurred: February 7, 2022, 7:55:04 PM (1 occurrences) 
Last logged: February 7, 2022, 7:55:04 PM

Not able to match sound mode: 'MULTI IN + DSUR', returning raw sound mode.

**Comment by ol-iver** [comment]
I created PR https://github.com/home-assistant/core/pull/70450 to include the new package version there.
