### ISSUE TITLE
Possible to query HDMI signal information?

### ISSUE THREAD

**Issue by sofakng** [ol-iver/denonavr#236]
Is it possible to retrieve the HDMI signal information (video/audio) using the Denon API?

The information is available through the Denon OSD:

Setup -> General -> Information -> Video -> HDMI Signal Info. [displays Resolution, Color Space, Pixel Depth]
Setup -> General -> Audio [displays Sound Mode, Input Signal, Sample Rate, Format]
![IMG_5599](https://user-images.githubusercontent.com/2228499/180296885-955c06f3-b6fb-42f4-850f-9052c2f2d6f2.JPEG)
![IMG_5598](https://user-images.githubusercontent.com/2228499/180296895-9230630d-2574-4503-88b0-d5c2df3d7ba7.JPEG)

**Comment by thetic** [comment]
.

**Comment by ol-iver** [comment]
Unfortunately, that's not possible. I have never seen any endpoint providing these information on my receiver.

**Comment by llamafilm** [comment]
@ol-iver this information is available in the Denon webpage.  Any idea how they get it there?  I would also love to be able to change audio delay via API, which can be done from that webpage.
<img width="837" alt="Screen Shot 2022-12-05 at 13 38 21" src="https://user-images.githubusercontent.com/3991046/205748291-47dd67ff-cd24-4cd8-8f64-6cf7d32ca533.png">
