### ISSUE TITLE
Quick Select?

### ISSUE THREAD

**Issue by tadly** [ol-iver/denonavr#24]
Not sure if I'm blind or if it isn't supported.

Is there a way to basically tell the avr to run/execute **Quick Select _n_**?
If it isn't, would it be possible to add?

Thanks for the module btw. :)

**Comment by ol-iver** [comment]
@Tadly 
completely missed your post :( sorry for that.
Atm quick select is not supported. I did not use this functionality so far. 
How could quick select being integrated to home assistant? This library is primarily created for HA and I don't get it how it could be used there.

**Comment by tadly** [comment]
Uff this issue is old ':D
My idea was "scenes" where you'd have a combination of input device, sound profile etc. (on the AVR), lighting, shutters and what not (home assistant) and quick select would have made the AVR part easy.

By now I do already have all that settled though so you don't have to add anything unless you feel like this would be a nice addition.

Personally I moved away from quick select and have those scenes setup in a script (easy to back up).

**Comment by ol-iver** [comment]
I don't see a proper way to integrate Quickselect to the media_player component in HA. Do you have anything in mind?

**Comment by tadly** [comment]
Oh I see what you're getting at. No,that's not possible in HA.
Specifically in HA, the media_player component could be extended to provide a service which would allow to execute commands (which is what I'm doing right now via shell scripts).

e.g. the [kodi media_player component](https://home-assistant.io/components/media_player.kodi/) does that (f.e the `KODI_CALL_METHOD` service)

Denon AVRs (I'd assume all of them) allow only one connection at a time so that's something to keep in mind :)

**Comment by ol-iver** [comment]
Ok, I got it.
I did not work with the quick select function yet. That's probably why I did not implement it :wink:
Btw. the one connection per receiver restriction is afaik only valid for the telnet interface. The HTTP interface this library is using, supports multiple connections. At least my receiver is supporting that.

**Comment by tadly** [comment]
There is an http interface? ._.
Does it support all the same things the telnet interface does?
I gotta rewrite some stuff than in that case ':D

**Comment by cajuncoding** [comment]
@Tadly,

Yes there is an Http interface, and this library has always used the Http interface.  In Home Assistant this is reflected in the "denonavr" component and not the "denon" platform.  The "denon" platform is telnet based, limited to 1 connection (as it's documented), etc. and was very unstable with the newer X sereis receivers -- basically didn't work reliably.  

However, the Http client is still there on recent X models, it's just changed a little, but the basic core functionality is still there, and is used by the Phone App, etc.

We did alot of digging/research and posted alot findings on [this thread here related to recent X model Denon receivers](https://github.com/scarface-4711/denonavr/issues/32).

**Comment by tadly** [comment]
@raerae1616 Uh awesome.
Thanks a lot for chiming in and linking that. Very much appreciated :)
