### ISSUE TITLE
Compile to EXE?

### ISSUE THREAD

**Issue by Ltek** [ol-iver/denonavr#25]
Anyone tried using Py2EXE to compile and run stand-alone?

My goal with this would be to run this stand-alone to be able to feed data to another app and allow that app to run the EXE as needed. The app is Homeseer.  Home runs VB and C# but doesnt work with Python.

thx for the info.

**Comment by ol-iver** [comment]
@Ltek sorry cannot help you with that. I never used Py2EXE.
Cheers,
Oliver
