### ISSUE TITLE
Auro-2D Surround missing from sound_mode

### ISSUE THREAD

**Issue by joggs** [ol-iver/denonavr#250]
Hi,
On my Marantz 7015 i have a sound mode named Auro-2D Surround
I can see in the const.py that it exists, but is grouped under Auro3d:
"AURO3D": ["AURO-3D", "AURO-2D SURROUND"],

I am primarily running this from home assistant, and when I set the receivers sound mode to Auro-2D Surround from my remote, I see the following properties in the denon itegration in home assistant
sound_mode: AURO3D
sound_mode_raw: Auro-2D Surround

For me, this looks like the integration selects AURO3D instead of the 2D alternative.
Is this by design, or could the constants be modified so it becomes a separate option?

Thanks

**Comment by joggs** [comment]
Is the project dead?

**Comment by ol-iver** [comment]
It is not dead. However, the time I spend here is limited.
I might have fixed it, according to a protocol description I found, but I cannot test it.
