### ISSUE TITLE
Request for Input-Format Commands

### ISSUE THREAD

**Issue by namornoditz** [ol-iver/denonavr#254]
This is my first post in github. Sorry if this is the wrong place!

I'm trying to include my Denon AVR in HomeAssistant.
I miss the sensors/commands for the current Audio-Input-Format.
The get_command option in HA does not response a value.

In Telnet I can use this Commands
Input Audio-Format: "SYSDA ?"
Input Channel Layout: "SSINFAISFOR ?"

**Comment by starkillerOG** [comment]
The input audio-format and layout also seem to be available under
`http://192.168.1.IP/SETUP/GENERAL/INFORMATION/d_information.asp`
Unfortunately I could not find them anywhere in the XMLs.

@ol-iver would it be possible for you to add the Telnet commands to at least store the status if the telnet interface is used?
I could make a PR in homeassistant to add a sensor platform to expose the input audio format and channel layout.

I am too instrested in using these for automations in HomeAssistant.

**Comment by namornoditz** [comment]
I made some pyhton scripts for my needs.
https://github.com/namornoditz/denon_avr_parameter

**Comment by ol-iver** [comment]
In the latest version you can [send telnet commands](https://github.com/ol-iver/denonavr/blob/d897e5926eda468526c7e0d1571479d85bdb637f/denonavr/denonavr.py#L229) in denonavr.
When you are interested in the reponse values, you could [register a callback](https://github.com/ol-iver/denonavr/blob/d897e5926eda468526c7e0d1571479d85bdb637f/denonavr/denonavr.py#L233) for these evente before.
When you are not interested in them anymore, you can [unregister them](https://github.com/ol-iver/denonavr/blob/d897e5926eda468526c7e0d1571479d85bdb637f/denonavr/denonavr.py#L239) again.

[This is an example](https://github.com/ol-iver/denonavr/blob/d897e5926eda468526c7e0d1571479d85bdb637f/denonavr/volume.py#L61) how the volume callback is registered. 

I'm not sure how to integrate this into HomeAssistant. The sending part is easy, but I'm not sure if it is possible to register custom callbacks for the responses.
I could give it a try when I finally released the new version.
