### ISSUE TITLE
Cannot increase timeout

### ISSUE THREAD

**Issue by Azenet** [ol-iver/denonavr#26]
Hi,

I am having an issue where the receiver's state will be off for one update(), then back on. I eventually found that the issue was that `/goform/formMainZone_MainZoneXmlStatus.xml` was sometimes taking more than 2 seconds to reply. Timeout is currently hardwired, would you consider adding a parameter to set the timeout when creating a DenonAVR device?

**Comment by ol-iver** [comment]
hi @Azenet ,
I'll include that to the next version.
Cheers,
Oliver

**Comment by ol-iver** [comment]
Included in version [0.5.3](https://github.com/scarface-4711/denonavr/releases/tag/0.5.3)
