### ISSUE TITLE
[Denon AVC-X4700H] Not able to match sound mode: 'NEURAL:X', returning raw sound mode.

### ISSUE THREAD

**Issue by iHaveAstream** [ol-iver/denonavr#261]
Hi,

I'm using HA 2023.9.2 and some Denon AVC-X4700H receiver.
When I set specific sound modes in the AVC, especially those related to "Neural:X", I usually get warnings in HA log that the sound mode cannot be matched. So it seems that the Denon integration cannot deal with "Neural:X" (and probably even other modes).
This happens ever since but I never had time to open an issue here. So I'm doing it now :)
The AVR is on latest available (online) firmware.

Here is an example from the HA Log:
`Logger: denonavr.soundmode
Source: components/denonavr/media_player.py:334
First occurred: 16:22:52 (1 occurrences)
Last logged: 16:22:52
Not able to match sound mode: 'NEURAL:X', returning raw sound mode.`

And here the extract from Developer Tools > States:
`source_list: 8K, AUX, Bluetooth, CBL/SAT, CD, DVD, Game, HEOS Music, Kodi, Phono, TV Audio, Tuner, UBP-X800M2
sound_mode_list: MUSIC, MOVIE, GAME, AUTO, STANDARD, VIRTUAL, MATRIX, ROCK ARENA, JAZZ CLUB, VIDEO GAME, MONO MOVIE, DIRECT, PURE DIRECT, DOLBY DIGITAL, DTS SURROUND, AURO3D, AURO2DSURR, MCH STEREO, STEREO, ALL ZONE STEREO
icon: mdi:audio-video
friendly_name: Denon AVC-X4700H
supported_features: 69004
volume_level: 0.33
is_volume_muted: false
media_content_type: channel
media_title: Kodi
source: Kodi
sound_mode: NEURAL:X
sound_mode_raw: NEURAL:X
dynamic_eq: true`

Many thanks in advance.

BR
Stefan

**Comment by ol-iver** [comment]
Which sound mode is active on your receiver when the `NEURAL:X` message is logged?

**Comment by iHaveAstream** [comment]
Hi,

right at the moment I'm watching football and the AVC shows Dolby Digital + Neural:X as a sound mode on its LCD display.
In HA log I see the error:

`Not able to match sound mode: 'DOLBY AUDIO - DD + NEURAL:X', assuming 'DOLBY DIGITAL'.`

and in Developer Tools (States) it says:

`source_list: 8K, AUX, Bluetooth, CBL/SAT, CD, DVD, Game, HEOS Music, Kodi, Phono, TV Audio, Tuner, UBP-X800M2
sound_mode_list: MUSIC, MOVIE, GAME, AUTO, STANDARD, VIRTUAL, MATRIX, ROCK ARENA, JAZZ CLUB, VIDEO GAME, MONO MOVIE, DIRECT, PURE DIRECT, DOLBY DIGITAL, DTS SURROUND, AURO3D, AURO2DSURR, MCH STEREO, STEREO, ALL ZONE STEREO
volume_level: 0.3
is_volume_muted: false
media_content_type: channel
media_title: Kodi
source: Kodi
sound_mode: DOLBY DIGITAL
sound_mode_raw: DOLBY AUDIO-DD+NEURAL:X
dynamic_eq: true
icon: mdi:audio-video
friendly_name: Denon AVC-X4700H
supported_features: 69004`

Again, I always see an error in HA logs when a sound mode with "Neural:X" has been set on the AVC. For some reason, the Integration cannot interpret this correctly.
Hope it helps. Thanks.

**Comment by ol-iver** [comment]
I just assigned both sound modes to `DOLBY DIGITAL`.

**Comment by iHaveAstream** [comment]
Hi there, I still get **warnings** in logs that are related to Neural:X sound mode, such as:

`Not able to match sound mode: 'M CH IN+NEURAL:X', returning raw sound mode.`

The integration works well for me, just those log warnings which are solely related to sound modes that are in context with "Neural:X" are a bit annoying ;-)
