### ISSUE TITLE
Not able to match sound mode: 'DOLBY PL2 MOVIE', assuming 'DOLBY DIGITAL'.

### ISSUE THREAD

**Issue by dCatfish** [ol-iver/denonavr#268]
**AVR model:**
Marantz SR5006

**HA log:**
Logger: denonavr.soundmode
Source: components/denonavr/media_player.py:362
First occurred: 10:52:07 AM (1 occurrences)
Last logged: 10:52:07 AM

Not able to match sound mode: 'DOLBY PL2 MOVIE', assuming 'DOLBY DIGITAL'.

**Comment by starkillerOG** [comment]
Will be fixed in PR: https://github.com/ol-iver/denonavr/pull/272

**Comment by dCatfish** [comment]
Thank you very much and Happy New Year @starkillerOG
