### ISSUE TITLE
Add remote control / system control capabilities

### ISSUE THREAD

**Issue by klada** [ol-iver/denonavr#289]
Right now there is no button navigation (cursor up/down/left/right/...) available through this library. This would however be very handy so the device could be controlled through IP entirely - no more IR remote would be required for navigating the setup menu.

Denon AVRs do support the following actions through the Telnet interface:

- Cursor Up: `MNCUP`
- Cursor Down: `MNCDN`
- Cursor Left: `MNCLT`
- Cursor Right: `MNCRT`
- Cursor Enter: `MNENT`
- Info button: `MNINF`
- Option button: `MNOPT`
- Back button: `MNRTN`
- Open setup menu: `MNMEN ON`
- Close setup menu: `MNMEN OFF`
- Get menu status: `MNMEN?` → Returns either `MNMEN ON` or `MNMEN OFF`.

HTTP control using these commands works as follows:

```
# Move cursor up
GET http://IP:8080/goform/formiPhoneAppDirect.xml?MNCUP
# Open setup menu
GET http://IP:8080/goform/formiPhoneAppDirect.xml?MNMEN%20ON
```

Note on the setup menu: It seems like the state can only be queried through Telnet (`MNMEN?` command). The phone app apparently maintains the setup menu's state (open or closed) internally and does not issue a `MNMEN?` query in order to toggle it.

**Comment by albaintor** [comment]
Hi, done in PR  https://github.com/ol-iver/denonavr/pull/290
