### ISSUE TITLE
Not able to match sound mode: 'DOLBY AUDIO-DD+', assuming 'DOLBY DIGITAL'.

### ISSUE THREAD

**Issue by Saarlothri** [ol-iver/denonavr#297]
I get a Warning of a missing Sound Mode

Logger: denonavr.soundmode
Quelle: components/denonavr/media_player.py:353
Erstmals aufgetreten: 11. August 2024 um 16:45:28 (1 Vorkommnisse)
Zuletzt protokolliert: 11. August 2024 um 16:45:28

Not able to match sound mode: 'DOLBY AUDIO-DD+', assuming 'DOLBY DIGITAL'.

**Comment by ol-iver** [comment]
Added with https://github.com/ol-iver/denonavr/pull/296
