### ISSUE TITLE
UPNP Play 

### ISSUE THREAD

**Issue by subutux** [ol-iver/denonavr#3]
Hi,

Would you be interested in supporting upnp play? I know that my denon avr (x1200) supports playing al url over upnp & have some code that supposedly works. 

This could add extra functionality for Home Assistant, allowing us to play, for example, TTS files.

Would you be interested in a pull request?

**Comment by ol-iver** [comment]
hej subutux,
would be interesting to see this working. Does it support audio only as the media server playback from the webinterface or is playing video files also supported?
keep going :)

**Comment by subutux** [comment]
Hi,

My Denon only supports audio playback (as stated in the manual & UI). Maybe other receivers support video playback.

I'll make the changes and test it out.

**Comment by bartberden** [comment]
Any update on this? Would love to have upnp playback to use TTS in home assistant with my Denon receiver.
