### ISSUE TITLE
Invalid album art

### ISSUE THREAD

**Issue by bmesuere** [ol-iver/denonavr#30]
When my receiver is playing content without album art (for example plain fm radio), Home Assistant keeps trying to load the unexisting album art for it. This is not a big problem, but when it tries loading the album art, for a fraction of a second, a square image show up in the control panel, before jumping back to the default.

Maybe denonavr can mark that there is no album art in this case?

The image it tries to load is:
```
https://*mylocalserver*/api/media_player_proxy/media_player.marantz?token=43b0d5633fa6ffc097436e452f19fa8e10eaf767b56b12da83f077cfb571ead2&cache=df4bb
```

**Comment by ol-iver** [comment]
@bmesuere, sorry I was off for a while.
I don't know how the image url you mentioned is generated as the library is using fixed urls
- http://{host}/NetAudio/art.asp-jpg?{timestamp as integer} - when there should be a real album art
- http://{host}/img/album%20art_S.png - for sources like the Tuner
Probably your receiver is redirecting one of those urls to the one you just posted. Could you please check?

**Comment by bmesuere** [comment]
Sorry for the delay in answering. I checked using the python interpreter:
```
>>> import denonavr
>>> d = denonavr.DenonAVR("192.168.0.3")
No mapping for audio source AUXC
Missing status information from XML for: FriendlyName
>>> d.image_url
'http://192.168.0.3/img/album%20art_S.png'
```

Requesting that image results in an error message with a status code of 404:
```
Access Error: Site or Page Not Found
Cannot open URL
```

It returns the same URL for both Tuner and AUXC.

Home Assistant on the other hand, only tries (and fails) to load album art if the source is set to Tuner:

```
volume_level: 0.1
is_volume_muted: false
media_content_type: channel
media_title: AUXC
source: AUXC
source_list: AUXA,AUXB,AUXC,AUXD,BD,CD,DOCK,DVD,DVR,GAME,HDRADIO,IPOD,IRADIO,LASTFM,M-XPORT,NAPSTER,NET/USB,PANDORA,PHONO,RHAPSODY,SAT/CBL,SERVER,SIRIUS,TUNER,TV,USB,USB/IPOD,V.AUX
friendly_name: marantz
supported_features: 3468
google_assistant_type: media_player 
```

```
volume_level: 0.06
is_volume_muted: false
media_content_type: music
media_title: 106.80
media_artist: DA
source: TUNER
source_list: AUXA,AUXB,AUXC,AUXD,BD,CD,DOCK,DVD,DVR,GAME,HDRADIO,IPOD,IRADIO,LASTFM,M-XPORT,NAPSTER,NET/USB,PANDORA,PHONO,RHAPSODY,SAT/CBL,SERVER,SIRIUS,TUNER,TV,USB,USB/IPOD,V.AUX
friendly_name: marantz
entity_picture: /api/media_player_proxy/media_player.marantz?token=9cac2d75f93d718c60662aad7cda51d01e5928b6817801c60d20c96996e43041&cache=8895b5346ddccbcb
supported_features: 3468
google_assistant_type: media_player
```

**Comment by ol-iver** [comment]
It seems that the album art URL is not working for Marantz receivers.

The library does not check if anything could be loaded from the URL, probably HA does. There is also a function in denonavr HA media_player component which determines when to show the entity picture.

Do you know a valid album art URL for your receiver?

**Comment by bmesuere** [comment]
Indeed, my receiver doesn't seem to support album art. The issue is that denonavr still reports (non-existing) album art, which the HA front end tries to display with layout artifacts as a result. Sorry if this wasn't clear from the initial report.

The request is thus: If there is a reliable way to detect that album art is not supported on the receiver, don't set that field in HA.

**Comment by ol-iver** [comment]
Finally I included a test, whether the image URL is accessible or not.
It is included to [this HA pull](https://github.com/home-assistant/home-assistant/pull/14551) request.
I'm closing this now. If the test is not working, please re-open.
