### ISSUE TITLE
identify_denonavr_receivers() returning None

### ISSUE THREAD

**Issue by trozen** [ol-iver/denonavr#34]
Not sure what is the point of this:
```
    if receivers:
        return receivers
    else:
        return None
```
but it doesn't seem to be the "pythonic" way. And because of this you can't do:
```
for denon in denonavr.discover():
    ...
```
Because NoneType is not iterable.

**Comment by ol-iver** [comment]
Changed in version 0.5.5.

**Comment by trozen** [comment]
Thanks!
