### ISSUE TITLE
Input mapping: ERROR:DenonAVR:No mapping for source Internet Radio

### ISSUE THREAD

**Issue by trantoriana** [ol-iver/denonavr#36]
AVR: Denon 3312
Source: Internet Radio
Source ID: NET/USB

INFO:homeassistant.core:Bus:Handling <Event state_changed[L]: new_state=<state media_player.denon3312=on; media_title=Internet Radio, source=Internet Radio, source_list=['BD', 'CD', 'DOCK', 'DVD', 'DVR', 'GAME1', 'GAME2', 'NET/USB', 'PHONO', 'SAT/CBL', 'TUNER', 'TV', 'V.AUX'], is_volume_muted=False, media_content_type=channel, friendly_name=Denon-3312, supported_features=3468, volume_level=0.02 @ 2017-12-09T12:42:25.456553+01:00>, old_state=None, entity_id=media_player.denon3312>

What can be done to fix this ?

Regards, Tran

**Comment by ol-iver** [comment]
Please download [this](https://github.com/scarface-4711/misc_python_tools/blob/master/denonavr/denon_receiver_xml.py) python script.
Start Internet Radio on your receiver and run the script like this `python denon_receiver_xml.py --host 192.168.0.250 --prefix AVR-3312`
You could send me the xml files the script stores to the directory you run it from. They include receiver‘s response of its http xml interface.

**Comment by trantoriana** [comment]
[denon-3312.zip](https://github.com/scarface-4711/denonavr/files/1554233/denon-3312.zip)

Too early to find your email address hence the attach.

Thanks, Tran

**Comment by kwv** [comment]
google found the thread, and I can't tell if it's related

From Home Assistant
```
No mapping for source SOURCE
8:38 PM components/media_player/denonavr.py (ERROR)
No mapping for source SOURCE
8:38 PM components/media_player/denonavr.py (ERROR)
Input function list for Denon receiver at host 10.0.1.170 could not be updated.
8:38 PM components/media_player/denonavr.py (ERROR)
Connection error: Receiver sources list empty. Please check if device is powered on.
8:38 PM components/media_player/denonavr.py (ERROR)
Host 10.0.1.170 returned malformed XML for: /goform/Deviceinfo.xml
8:38 PM components/media_player/denonavr.py (ERROR)
```

[AVR-X4200W.zip](https://github.com/scarface-4711/denonavr/files/1680220/AVR-X4200W.zip)

**Comment by ol-iver** [comment]
@trantoriana sorry for getting back to you so late, but the issue should be fixed in the meantime anyhow

@kwv the root cause of your error messages should be a connection or a receiver error. I have the same Denon model and occasionally it happens that its web interfaces are crashing somehow and do not respond anymore. Usually unplugging and replugging helps in those cases

Closing this issue now. If it still occurs, please reopen it.
Cheers.
