### ISSUE TITLE
DENON AVR-4306

### ISSUE THREAD

**Issue by denbertuz** [ol-iver/denonavr#39]
Hi There,

I have a very old Denon AVR-4306 - works perfect with web interface and the AVR-Remote app https://play.google.com/store/apps/details?id=de.pskiwi.avrremote

I've added the following to my configuration.yaml:

media_player:
  - platform: denonavr
    host: 192.168.1.11
    name: AVR-4306
    show_all_sources: True
    timeout: 4

I can see the machine, but it don't show correct state and it don't work.

Is the protocol used in this old machine suitable for the denonavr or should I forget it?

**Comment by ol-iver** [comment]
hi @denbertuz,
could you please run the python script you find here:
https://github.com/scarface-4711/misc_python_tools/tree/master/denonavr
This will save your receivers response to the HTTP requests to your disk. Maybe I can help you when you upload those files here.

**Comment by denbertuz** [comment]
Hi @scarface-4711 

I've finally found time to test it - trying from my Ubuntu Mate 16.04 LTS - and are getting the following:

```
$ python denon_receiver_xml.py --host 192.168.1.72 --prefix AVR-4306
  File "denon_receiver_xml.py", line 1
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

Thanks for pointing me in the right direction, as I'm clearly doing something wrong here!

**Comment by ol-iver** [comment]
It's looking like you saved the whole github HTML page and not the script. That's why it is not working.

**Comment by denbertuz** [comment]
OMG!!!! - Thanks - I'll try again in the weekend and report back
