### ISSUE TITLE
Support for Marantz

### ISSUE THREAD

**Issue by seanb-uk** [ol-iver/denonavr#4]
I wondered if you'd be interested in adding support for Marantz? The API looks very similar to Denon, and in fact it more or less works out of the box (I'm using it in HomeAssistant for my M-CR610).

I haven't tried all of the functions, but powering on, selecting sources and changing volume all work. The only issue so far is that the mute status and volume aren't shown.

On the Marantz, the MAINZONE_URL doesn't return MasterVolume or Mute. They're both returned by the STATUS_URL, which unfortunately doesn't supply FriendlyName (which is still in MAINZONE_URL). Since FriendlyName is unlikely to change, I figure it's fine to get that at init time and use STATUS_URL for getting volume and mute status.

Doesn't seem worth a dedicated fork just for those changes. The DEVICEINFO_URL returns BrandCode and ModelName, either of which might be options to choose the URLs?

**Comment by ol-iver** [comment]
Sounds promising. If it's just the volume, I would say we could integrate it here. I just checked some technical data of your Marantz. Did you also test the streaming features like Airplay, DLNA?
It would be great if you upload example files of all the **_URLs** here.

**Comment by seanb-uk** [comment]
It's volume and mute, and I've discovered a few other issues.

Analog inputs AUX2 and AUX3 can't be selected. For some reason they're known as AUXB and AUXC and must be selected by those names, although I can't see any mapping to indicate that in the device info. That's what they show up as when selected manually via the remote or iOS app.

I also don't see any favourites in the XML, even though the iOS app can see them.

I haven't tried Airplay or DLNA yet as I don't really use them but I'll try to have a play at some point.

[mcr610-xml.txt](https://github.com/scarface-4711/denonavr/files/771147/mcr610-xml.txt)


I've attached the XML outputs anyway

**Comment by ol-iver** [comment]
Unfortunately the developers of the webinterface/smartphone apps put some logic, especially the mapping of variables, into the JavaScripts of the pages. Thus the overall logic is a bit hard to understand. I already spent some time to figure this out for my Denon. I am off for a few days, but I will try to do the same with your files when I'm back :-)

**Comment by seanb-uk** [comment]
OK, now I've had a bit of play with the code, I see this is what you're doing in SOURCE_MAPPING.

Adding the following entries to the dictionary sorts that out and let's me select them:

'Analog In 1': 'AUXB', 'Analog In 2': 'AUXC'

Getting STATUS_URL instead of MAINZONE_URL in the update function gets the volume and mute status correctly. I then forced _get_renamed_deleted_sources to use MAINZONE_URL and picked up FriendlyName there.

All network functions show up as "NET" - the actual net function is held in NetFuncSelect returned by MAINZONE_URL and not STATUS_URL - which means to determine the actual function it's necessary to query both.

**Comment by seanb-uk** [comment]
Found another way - see attached.

[AppCommandXmloutput.txt](https://github.com/scarface-4711/denonavr/files/791589/AppCommandXmloutput.txt)
 
It calls goform/AppCommand.xml with a POST body content that contains the commands to run. This gets everything needed, including the mappings I need for AUXB and AUXC and the favourites.

The iOS app calls the DEVICEINFO_URL, then does the POST from the attached example to get the renames. I've also discovered that you can add another command, GetFriendlyName, which does as you'd expect. It then repeatedly POSTs the request for power, volume etc...

Luckily the iOS app lets you set an IP address for the device, so I got this by pointing at an Apache instance that was configured to proxy all requests to my actual Marantz. It was either that or get a long enough ethernet cable to attach it to my router so I could sniff the traffic!

It might be worth trying these on your Denon - this could be an approach that works across all devices and removes the need for source mapping?

**Comment by ol-iver** [comment]
AppCommand.xml is also working for my receiver. But at least for the Denon receivers the mapping would still be necessary. My receiver is presenting the renaming information in MainZoneXmlStatus.xml too, but there are some sources which have a different name for getting than for setting (eg. "TV AUDIO" vs. "TV" and "CBL/SAT" vs. "SATCBL" for whatever reason). I think we could make the mapping optional for those cases and use the for the rest.
I start working on that and the other things you pointed out. When I'm finished I'll upload a new version for testing.

**Comment by ol-iver** [comment]
It took a while. Sorry for that, I had some other things on my agenda. But finally I did it.
Could you please test the latest sources here from github? Currently the sources are not at pypi yet, because it's probably a good idea, if someone with a real Marantz receiver could test first.

**Comment by seanb-uk** [comment]
I had a really quick look, and this version has fixed the volume and mute status, but I'm still having trouble with the source selects  - I hope to get some more time over the weekend to dig into it and see what's happening.

**Comment by ol-iver** [comment]
The Marrantz interface seems to name the functions even more inconsistent then Denon interface is doing.
In AppCommand.xml the function is called AUXB at the renaming section, whereas the FuncName of the same function is AUX2 some lines below in the delete section. 
Deviceinfo.xml uses AUX2 again.
If you send a source selection command it should be called AUXB according to your description.

I'm now wondering how it is called in MainZoneXml.xml in the InputFuncSelect tag when you have selected it. 
Could you please send me an example for this  XML and additionally the response of following POST for AUXB and some NET functions selected?

`<?xml version="1.0" encoding="utf-8"?>
<tx>
 <cmd id="1">GetAllZonePowerStatus</cmd>
 <cmd id="1">GetVolumeLevel</cmd>
 <cmd id="1">GetMuteStatus</cmd>
 <cmd id="1">GetSourceStatus</cmd>
</tx>`

For "Internet Radio" it is the same thing. It is called "Internet Radio" but also "IRADIO".

I just added the entries to the dictionary, that you are able to switch.
NET functions are not done yet. Example files from above would help.

**Comment by seanb-uk** [comment]
The MainZoneXML.xml InputFuncSelect always seems to show the functionrename rename value, except for net connections where it shows "NET" and NetFuncSelect shows the rename - eg:

```
<InputFuncSelect><value>NET</value></InputFuncSelect>
<NetFuncSelect><value>IRADIO</value></NetFuncSelect>
```

Or 

```
<InputFuncSelect><value>TUNER</value></InputFuncSelect>
<NetFuncSelect><value>IRADIO</value></NetFuncSelect>
```

NetFuncSelect will show the last selected network function, but this only applies if InputFuncSelect is "NET" - otherwise it's ignored.

The AppCommand query including GetSourceStatus shows the rename - eg:

```
<cmd>
<source>TUNER</source>
</cmd>
```

Or:

```
<cmd>
<source>AUXC</source>
</cmd>
```

Except for Internet Radio, which instead of IRADIO shows:

```
<cmd>
<source>Internet Radio</source>
</cmd>
```

The same applies to SERVER, which has a source of "Music Server"

So the network ones seems to be using the FuncName from GetDeletedSource or GetDeletedNetworkSource, but the others are using the names from GetRenameSource.

It's definitely inconsistent. The names used to select functions are always the names from the functionrename list. It's the source displayed by AppCommand that's inconsistent.

**Comment by bmesuere** [comment]
I've also got a marantz receiver (M-CR603) and would like to help if needed. On mine, the different aux inputs are called AUXA-AUXD internally (the physical interface on the device lists them as AUX1-AUX4).

**Comment by ol-iver** [comment]
Found out that your Marantz receivers behave more like Denon AVR-nonX devices.
Please try the latest version on github. Did not realize the NET functions so far, I'll do so if this damn AUX thing is working ;-)

**Comment by seanb-uk** [comment]
OK, good news - the AUX functions are working!

For the net functions, it's not sufficient to get InputFuncSelect from STATUS_URL as this will just say "NET". The NetFuncSelect from MAINZONE_URL specifies which net function (e.g. IRADIO, SERVER). Setting them works fine for the mappings, but then the update fails:

```
>>> d.input_func_list
['Analog In 1', 'Analog In 2', 'CD', 'Digital In', 'Front USB', 'Internet Radio', 'Last.fm', 'Media Server', 'Music Server', 'Rear USB', 'Spotify', 'Tuner']
>>> d.input_func = "Internet Radio"
>>> d.update()
No mapping for network audio source NET
True
>>> d.input_func
'NET'
```
Using AppCommand with the GetSourceStatus returns the value but it's inconsistent - for normal functions it shows name (e.g. CD, TUNER, AUXB) but for the net functions it shows the rename (e.g. "Music Server", "Internet Radio"). It looks like it's using the DefaultName and FuncName mappings from GetDeletedNetworkSource. GetDeletedSource doesn't seem to be used, although this might just be for my device.

A single call to AppCommand might be the best way to get the status, but then it would need mappings from display name to function name and from AppCommand source name to display name.

It's also picking up media server as a source, but that's not valid. 

Without access to other devices, I'm not sure if there's a way of getting a module that works for both Denon and Marantz without lots of special cases.

It's really frustrating isn't it!? Denon and Marantz are so similar but just different enough to be annoying!

**Comment by bmesuere** [comment]
I'll take a look at it next week when I'm back from vacation.

**Comment by ol-iver** [comment]
you're right it is pretty annoying...that's why I had to take several days off from receiver stuff ;)
Please check the latest version, if the network functions are now displayed correctly. Additionally you should check if you could still switch to "Internet Radio". I temporary removed a static mapping for Internet Radio and Media Server, because I was not sure, if this was right or not.
Btw. I prefer using the HTTP GET interface whenever it is possible. It's much easier getting test files for this, than for the HTTP POST.

**Comment by seanb-uk** [comment]
Yes, it looks like it's all working now, including Internet Radio. Copying it into HomeAssistant also now picks up the correct labels in the source drop down, and is showing some of the graphics. For example, I get the logos for internet radio stations but not the cover art from music server music (which does show in the Marantz remote app). One for another time though - I'm happy just to be able to reliably select inputs :)

Thanks for your efforts, and let me know if there's anything else I can help test on this device.

**Comment by bmesuere** [comment]
@seanb-uk How did you manage to load the dev version into Home Assistant?

**Comment by seanb-uk** [comment]
@bmesuere I just copied the new version of denonavr.py into the config/deps/denonavr directory under my HA home directory and restarted HA.

This might not survive HA updates if it refreshes the dependencies, but it was sufficient for testing.

**Comment by ol-iver** [comment]
You're welcome :)
Could you check how the image is coming to the remote app?
The library is not getting the image directly, it is providing a link to homeassistant which is downloading the image then. 
This is an example of an URL. At my receiver all the covers logos etc. could be found at the same URL for Internet Radio and for Spotify, Media Server etc. depending which source is currently active. It's built up like this: http://192.168.0.23/NetAudio/art.asp-jpg?1492553221
Maybe it is somehow different at your receiver.
There is also a seconds URL, but it is just showing a static image http://192.168.0.23/img/album%20art_S.png

**Comment by ol-iver** [comment]
Just found the issue about the music server logos. It should work now in the latest version :)

**Comment by seanb-uk** [comment]
Perfect timing - I had a go this morning, but couldn't get media server working via a proxy, so I was going to have trouble finding the URL from the remote app.

The latest fix works, it's picking up the cover art from the DLNA music server source.

**Comment by ol-iver** [comment]
Good news :)
I just pushed the module to version 0.4.0 and created a pull request for homeassistant, that it is going to be included there.
If you want to track it... https://github.com/home-assistant/home-assistant/pull/7250

I'll close this here. If there are any issue, just open it again.

**Comment by bmesuere** [comment]
I finally got around to testing this (inside home-assistant). I noticed 2 issues:
- When my receiver is on an aux input, I get the error message `No mapping for audio source AUXD`
- When I use one of the radio options, I get the error `No mapping for audio source TUNER` and there is no distinction between the DAB, FM and AM tuner.

**Comment by ol-iver** [comment]
@seanb-uk: Could you test if the latest version from GIT is still working for you?
I added support for multiple zones and redesigned some parts of the Main Zone because the other zones do not have an equivalent to MAINZONE_URL for some reason.
Please see my comment here https://github.com/scarface-4711/denonavr/issues/8#issuecomment-307602917

**Comment by seanb-uk** [comment]
Yes, still working for me :)
