### ISSUE TITLE
Custom name for input source no longer used in HA

### ISSUE THREAD

**Issue by jobi** [ol-iver/denonavr#42]
After updating Home Assistant to 0.64.3, the denonavr component started to list the default names for my Marantz NR1506, rather than the custom names I configured. I'm not sure this is a expected? It was nice to have the custom names come through ("Chromecast" vs "AUX").

**Comment by ol-iver** [comment]
Really? That should not happen.
Could you execute the python script from the following repo and upload the resulting XML files? I will check it then.
https://github.com/scarface-4711/misc_python_tools/tree/master/denonavr
