### ISSUE TITLE
media_player.volume_mute doesn't work

### ISSUE THREAD

**Issue by vehsen** [ol-iver/denonavr#44]
Home Assistant 0.64.3 // Denon AVR-X2200W

media_player.volume_mute works neither as

```
  action:
    - service: media_player.volume_mute
      entity_id: media_player.denon_avr
```

nor as dev-service

```
media_player.volume_mute
{
  "entity_id": "media_player.denon_avr"
}
```

> Log Details (ERROR)
> Tue Mar 06 2018 17:53:17 GMT+0100 (Central Europe Standard Time)
> 
> Invalid service data for media_player.volume_mute: required key not provided @ data['is_volume_muted']. Got None

**Comment by ol-iver** [comment]
That's nothing related to this library. Your calls in HA are looking wrong.

Try this to mute:
```
media_player.volume_mute
{
  "entity_id": "media_player.denon_avr"
  "is_volume_muted": "true"
}
```
and that to unmute:
```
media_player.volume_mute
{
  "entity_id": "media_player.denon_avr"
  "is_volume_muted": "false"
}
```
