### ISSUE TITLE
Power State is "flickering" on pre 2016 AVR

### ISSUE THREAD

**Issue by ffittschen** [ol-iver/denonavr#47]
Hi,

whenever my AVR-X2300W is **on**, Home Assistant sometimes displays it as being **off** for a brief moment (see screenshot).
I traced the issue back to potentially being in [denonavr.py#L413](https://github.com/scarface-4711/denonavr/blob/master/denonavr/denonavr.py#L413).

The comment says _On timeout and connection error, the device is probably off_, but I'd argue that connection errors or timeouts can also be due to the bad WiFi capabilities of the AVR, so at least in my case the state probably hasn't changed.

I don't know the original reasoning behind the choice of setting the state to `POWER_OFF` on connection errors and timeouts, but I'd propose that it should only change the state if `self._power == None` and not blindly set it to `POWER_OFF`, but rather keep the current state if it is not `None`.

What do you think of that?

------
Screenshot in the Home Assistant History view displaying a timespan of 1 day:

![screen shot 2018-06-07 at 21 17 10](https://user-images.githubusercontent.com/7734806/41121873-e9be3ffc-6a99-11e8-9464-e2158742a591.png)

**Comment by ol-iver** [comment]
Hello @ffittschen,
initially the library did not change the power status on connection errors. It turned out, that some receivers are not responding to requests on their network interface, when they are switched off. Those devices could not get to the offline state and that's why I changed the behavior.
Did you try to increase the timeout for denonavr in HA? Its default is set to 2 seconds.

**Comment by ffittschen** [comment]
Ahh I see, and that behavior doesn't surprise me at all... All of the official networking parts (website, app, OTA updates) of my receiver feel so hacky.. 

No I didn't try it because I thought 2 seconds would be more than enough on a local network. I increased it to 15 seconds now and the state seems to be more stable.

Thanks!
