### ISSUE TITLE
Issue with getting AVR-S940H functioning with denonavr

### ISSUE THREAD

**Issue by bluepixel00** [ol-iver/denonavr#51]
I am having issues with getting an AVR-S940H working with home assistant (unable to get status or turn/off unit).  This is a newer model but I am able to access the unit through the web interface as well as through the denon mobile app.

I was successfully able to turn on / off device using the following commands in a browser/postman.
http://10.0.1.172:8080/goform/formiPhoneAppDirect.xml?PWSTANDBY
http://10.0.1.172:8080/goform/formiPhoneAppDirect.xml?PWON

**configuration.yaml**
media_player:
  - platform: denonavr
    host: 10.0.1.172

**Home assistant log details:**
2018-06-30 22:19:51 ERROR (SyncWorker_8) [DenonAVR] Missing status information from XML of Main for: Power, InputFuncSelect, Mute, MasterVolume, selectSurround, SurrMode
2018-06-30 22:20:01 ERROR (SyncWorker_7) [DenonAVR] Host 10.0.1.172 returned HTTP status code 403 to GET request at end point /goform/formMainZone_MainZoneXmlStatus.xml
2018-06-30 22:20:02 ERROR (SyncWorker_7) [DenonAVR] Host 10.0.1.172 returned HTTP status code 403 to GET request at end point /goform/formMainZone_MainZoneXml.xml

**denon_reciever_xml.py output**
HTTP Status Code of /goform/AppCommand.xml: 403
HTTP Status Code of /goform/AppCommand.xml: 403
HTTP Status Code of /goform/Deviceinfo.xml: 403
HTTP Status Code of /goform/formMainZone_MainZoneXmlStatus.xml: 403
HTTP Status Code of /goform/formMainZone_MainZoneXml.xml: 403
HTTP Status Code of /goform/formNetAudio_StatusXml.xml: 403
HTTP Status Code of /goform/formTuner_TunerXml.xml: 403
HTTP Status Code of /goform/formTuner_HdXml.xml: 403
HTTP Status Code of /goform/formZone2_Zone2XmlStatus.xml: 403
HTTP Status Code of /goform/formZone3_Zone3XmlStatus.xml: 403
HTTP Status Code of /goform/AppCommand.xml: 200
HTTP Status Code of /goform/AppCommand.xml: 200
HTTP Status Code of /goform/Deviceinfo.xml: 200
HTTP Status Code of /goform/formMainZone_MainZoneXmlStatus.xml: 403
HTTP Status Code of /goform/formMainZone_MainZoneXml.xml: 403
HTTP Status Code of /goform/formNetAudio_StatusXml.xml: 403
HTTP Status Code of /goform/formTuner_TunerXml.xml: 403
HTTP Status Code of /goform/formTuner_HdXml.xml: 403
HTTP Status Code of /goform/formZone2_Zone2XmlStatus.xml: 403
HTTP Status Code of /goform/formZone3_Zone3XmlStatus.xml: 403

As the above shows I am getting 403, access denied on all requests EXCEPT:
AppCommand-2016-8080-200.xml
AppCommand-8080-200.xml
Deviceinfo.xml-8080-200.xml

Am I doing something wrong?  Thanks for any help.

**Comment by ol-iver** [comment]
Could you please upload the xml files generated by **denon_reciever_xml.py**?
I can have a look at it then.

**Comment by bluepixel00** [comment]
xml files are attached. Thanks.  

[AVR-S940H.tar.gz](https://github.com/scarface-4711/denonavr/files/2174332/AVR-S940H.tar.gz)

**Comment by bluepixel00** [comment]
I ended up returning the AVR-S940H and got an older model that works without any issue.  This would be an issue with any new units but if you want you can close this issue since I will not be able to validate any fix.

**Comment by Waster1994** [comment]
Sorry to jump in on this thread, but I have exactly the same issue with my AVC-8500H amp (xml files generated by 'denon_receicer_xml.py' attached).

[AVC-8500H.zip](https://github.com/scarface-4711/denonavr/files/2259509/AVC-8500H.zip)
