### ISSUE TITLE
Not able to match sound mode, returning raw sound mode

### ISSUE THREAD

**Issue by coalfield** [ol-iver/denonavr#58]
Error showing up on Hassio (Home Assistant) 1.7

> 2018-07-29 22:10:46 WARNING (SyncWorker_4) [DenonAVR] Not able to match sound mode, returning raw sound mode.
> 2018-07-29 22:10:57 WARNING (SyncWorker_9) [DenonAVR] Not able to match sound mode, returning raw sound mode.
> 2018-07-29 22:11:08 WARNING (SyncWorker_6) [DenonAVR] Not able to match sound mode, returning raw sound mode.
> 2018-07-29 22:11:19 WARNING (SyncWorker_12) [DenonAVR] Not able to match sound mode, returning raw sound mode.
> 2018-07-29 22:11:30 WARNING (SyncWorker_14) [DenonAVR] Not able to match sound mode, returning raw sound mode.
> 2018-07-29 22:11:41 WARNING (SyncWorker_4) [DenonAVR] Not able to match sound mode, returning raw sound mode.

This is with STEREO sound with the receiver on or off

**Comment by ol-iver** [comment]
Already fixed
https://github.com/scarface-4711/denonavr/issues/57

**Comment by coalfield** [comment]
thank you, I will await for it to update into hassio.
