### ISSUE TITLE
Not able to match sound mode: Multi In + Neural:X 

### ISSUE THREAD

**Issue by thegunslingers** [ol-iver/denonavr#59]
Not able to match sound mode so it appears this sound mode needs to be added. 

Thank you in advance 

source: Game 
sound_mode: Multi In + Neural:X 
media_title: Game 
media_content_type: channel 
sound_mode_raw: Multi In + Neural:X

**Comment by starkillerOG** [comment]
[This PR](https://github.com/scarface-4711/denonavr/pull/61) will add the sound mode.

**Comment by ol-iver** [comment]
Available in [0.7.6](https://github.com/scarface-4711/denonavr/releases/tag/0.7.6)
