### ISSUE TITLE
SR5006 Zone2 Source List Not Available

### ISSUE THREAD

**Issue by TimothyLeeAdams** [ol-iver/denonavr#60]
I started having a problem with my Zone2 sources several weeks ago, after updating Home Assistant. I'm not sure which version though, unfortunately...  

Zone2 sources do not appear in the **source_list** field, and I am unable to change Zone2 sources using the services tool in HA. All other Zone2 functions (power, volume, mute, etc.) still work, however. In Home Assistant, the error log shows the following two errors:
`Input function list for Denon receiver at host 192.168.1.127 could not be updated.`
and 
`Receiver sources list empty. Please check if device is powered on.`
These error log entries appear about 6 times a minute, presumably because this is the update interval.

I ran the **denon_receiver_xml.py** and have attached my XML files for your reference: [xml_test_sr5006.zip](https://github.com/scarface-4711/denonavr/files/2275687/xml_test_sr5006.zip)

Are there any further tests I can run to try and determine what is causing the issue? The XML for Zone2 appears normal, and has the sources listed, so I'm not sure where else to look...

I'm not entirely sure whether this is an issue with denonavr, or whether the media_player implementation of Zone2 controls in HA has changed, so my apologies in advance if I'm not posting this issue in the correct repo.

**Comment by TimothyLeeAdams** [comment]
UPDATE: 
I was able to work out a ~~fix~~ hack to resolve this issue for my setup. Looking at the definition of Zone 2 URLs, I noticed that the MAINZONE_Z2_URL variable is set to None:
```
# Zone 2 URLs
STATUS_Z2_URL = "/goform/formZone2_Zone2XmlStatus.xml"
MAINZONE_Z2_URL = None
COMMAND_SEL_SRC_Z2_URL = "/goform/formiPhoneAppDirect.xml?Z2"
COMMAND_FAV_SRC_Z2_URL = "/goform/formiPhoneAppDirect.xml?Z2"
COMMAND_POWER_ON_Z2_URL = "/goform/formiPhoneAppPower.xml?2+PowerOn"
COMMAND_POWER_STANDBY_Z2_URL = "/goform/formiPhoneAppPower.xml?2+PowerStandby"
COMMAND_VOLUME_UP_Z2_URL = "/goform/formiPhoneAppDirect.xml?Z2UP"
COMMAND_VOLUME_DOWN_Z2_URL = "/goform/formiPhoneAppDirect.xml?Z2DOWN"
COMMAND_SET_VOLUME_Z2_URL = "/goform/formiPhoneAppVolume.xml?2+%.1f"
COMMAND_MUTE_ON_Z2_URL = "/goform/formiPhoneAppMute.xml?2+MuteOn"
COMMAND_MUTE_OFF_Z2_URL = "/goform/formiPhoneAppMute.xml?2+MuteOff"
```
I hope I can be forgiven for my lack of Python skills, but I can't determine why this variable would not be defined here. When I give this variable a definition, using the same value as MAINZONE_URL, Zone 2 works correctly and now has a populated source list. I modified as follows:
```
# Zone 2 URLs
STATUS_Z2_URL = "/goform/formZone2_Zone2XmlStatus.xml"
MAINZONE_Z2_URL = "/goform/formMainZone_MainZoneXml.xml"
COMMAND_SEL_SRC_Z2_URL = "/goform/formiPhoneAppDirect.xml?Z2"
COMMAND_FAV_SRC_Z2_URL = "/goform/formiPhoneAppDirect.xml?Z2"
COMMAND_POWER_ON_Z2_URL = "/goform/formiPhoneAppPower.xml?2+PowerOn"
COMMAND_POWER_STANDBY_Z2_URL = "/goform/formiPhoneAppPower.xml?2+PowerStandby"
COMMAND_VOLUME_UP_Z2_URL = "/goform/formiPhoneAppDirect.xml?Z2UP"
COMMAND_VOLUME_DOWN_Z2_URL = "/goform/formiPhoneAppDirect.xml?Z2DOWN"
COMMAND_SET_VOLUME_Z2_URL = "/goform/formiPhoneAppVolume.xml?2+%.1f"
COMMAND_MUTE_ON_Z2_URL = "/goform/formiPhoneAppMute.xml?2+MuteOn"
COMMAND_MUTE_OFF_Z2_URL = "/goform/formiPhoneAppMute.xml?2+MuteOff"
```
I'm guessing that this variable must be set somewhere else for Zone 2, because that part of the code doesn't seem to have changed  since it was added, and up until sometime in summer 2018, Zone 2 functionality was working correctly for me. However, as I mentioned, my Python chops are not where I wish they were.

I'm not sure if this helps anyone understand the nature of the problem, but I hope it does. I'm currently learning Python almost entirely to be able to fix this issue myself and hopefully submit a pull request eventually, but that is probably going to take a while. However, if anyone has any ideas or suggestions, any pointers in the right direction are welcomed.

**Comment by notgwj** [comment]
I have the same problem with my AVR-3312CI.  Here's the output from denon_receiver_xml.py: [AVR-3312CI.zip](https://github.com/scarface-4711/denonavr/files/3183843/AVR-3312CI.zip).  

Is there any reason not to get the list of inputs for Zone2/3 from either the Main Zone (includes info about deleted inputs) or from the formZone2_Zone2XmlStatus.xml?  Failing either of those, maybe we could pass in a list of possible inputs for each zone?

**Comment by TimothyLeeAdams** [comment]
I’d recommend downloading the component and modifying it as I did - it’s worked well for me. For reasons I’m not able to deduce, it doesn’t seem like there’s much interest from anyone else to work on a proper fix.

**Comment by notgwj** [comment]
I will probably do that, but I'd much prefer to not need to maintain local changes.  I'd also like to improve the experience for others by getting a proper fix in.  The current behavior seems broken to me for Zones2/3 on receivers such as ours.  I'm happy to submit a PR to make it work, but I want to understand the maintainer's perspective on which method makes the most sense.

Thank you for filing this issue and providing a workaround.

**Comment by TimothyLeeAdams** [comment]
Oh great! I agree, the current functionality seems broken to me as well. If you decide to work on this, I’ll be happy to help to test on my receiver.
