### ISSUE TITLE
Couple of not able to match sound modes

### ISSUE THREAD

**Issue by lviperz** [ol-iver/denonavr#62]
sound_mode_raw: Dolby D + +Dolby Surround 
sound_mode: DOLBY D + +DOLBY SURROUND

sound_mode_raw: Dolby D + Neural:X 
sound_mode: DOLBY D + NEURAL:X

**Comment by starkillerOG** [comment]
[This PR](https://github.com/scarface-4711/denonavr/pull/61) will add those sound modes and fix this issue.

**Comment by ol-iver** [comment]
Available in [0.7.6](https://github.com/scarface-4711/denonavr/releases/tag/0.7.6)
