### ISSUE TITLE
Current Playing Audio-Stream 

### ISSUE THREAD

**Issue by kdvlr** [ol-iver/denonavr#7]
Is it possible to get the current playing audio stream or any media (audio/video) information? 

I am essentially trying to dim lights when playing media, but my Fire TV and my vizio are not supported, so the Denon seems like a good place and it has all the information available to identify the type of media. 

I can see this info in the Denon iOS App. If so, can it be available with the denonavr component ?

**Comment by ol-iver** [comment]
My receiver does not seem to stream any video or audio data. I have a 2015 model which is also not supported by the latest "AVR Remote" app. Maybe that changed over the time, but I have never seen a receiver which is streaming audio or video data to the network. 
But do you really need an audio stream to dim your lights or won't be some attributes sufficient for that?
For the later case there some attributes like _state_, _artist_, _title_ or even _input_func_ you might use.

**Comment by kdvlr** [comment]
I was not clear on my requirement. I don't need an audio stream to be played. 

I need the lights to dim whenever I play a Dolby Digital or DTS stream, because that means I am watching a movie. If it is just stereo, it's probably a youtube stream or regular TV. 

I noticed that this information is available in /goform/formMainZone_MainZoneXmlStatus.xml as 
```xml
<SurrMode><value>Stereo</value></SurrMode>
```

Now. I need to figure out how to get this information into HomeAssistant.

**Comment by ol-iver** [comment]
It would be easy to include that attribute to this module, but this won't help much as the media_player component in homeassistant does not support an attribute like this.

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/media_player/__init__.py
Starting at line 60 you find all attributes of media_players listed: **ATTR_...** 

As this would affect all media player devices, you should probably create a feature request to add additional attributes for media_player devices first. Maybe you find other supporters.
https://community.home-assistant.io/c/feature-requests

**Comment by kdvlr** [comment]
Thank you for the quick response. I'll put in a request. 

Meanwhile, I see you're not using Media Content Id . Could it possibly be used instead ? 

Edit: Here's the feature request link in case you want to monitor - https://community.home-assistant.io/t/additional-codec-attribute-for-media-player-devices/16270

**Comment by ol-iver** [comment]
hej @kdvlr,
sorry for not responding, but I was on vacation.
I checked the demo implementation of homeassistant for the content_id and there it is used to uniquely identify the content (e.g. channel or title...) which is actually played. I don't think that this attribute is supposed to be used to show the format of the audio stream.
cheers,
Oliver

**Comment by kdvlr** [comment]
Thanks Oliver. I am using an input string in HASS to get the information.
