### ISSUE TITLE
Denon AVR X3100W

### ISSUE THREAD

**Issue by jazbraz** [ol-iver/denonavr#73]
Thu Jan 17 2019 21:50:37 GMT+0100 (centraleuropeisk normaltid)

Not able to match sound mode: 'PLIIx Cinema', returning raw sound mode.

**Comment by starkillerOG** [comment]
@jazbraz I included 'PLIIx Cinema' to my PR, so it will be fixed as soon as that gets merged.

**Comment by ol-iver** [comment]
This is included in version 0.7.8 now.
