### ISSUE TITLE
DENON AVR-1912

### ISSUE THREAD

**Issue by alilaa** [ol-iver/denonavr#74]
Not able to match sound mode: 'MCH STEREO', returning raw sound mode.

sound_mode: STEREO
sound_mode_list: MUSIC,MOVIE,GAME,AUTO,VIRTUAL,PURE DIRECT,DOLBY DIGITAL,DTS SURROUND,MCH STEREO,STEREO,ALL ZONE STEREO
sound_mode_raw: STEREO
friendly_name: DENON:[AVR-1912]
supported_features: 69004

**Comment by ol-iver** [comment]
Just included a fix in version 0.7.8.
