### ISSUE TITLE
Sound mode ALL_ZONE_STEREO to sticky

### ISSUE THREAD

**Issue by DanskerUS** [ol-iver/denonavr#78]
Hi, thanks for all the work the denonavr module.

Using the sound modes: after ALL_ZONE_STEREO I can no longer switch to the other sound modes. 

It is a special Denon feature, that ALL_ZONE_STEREO must be OFF, or you cannot set any of the other sound modes.

Just like in Harmony Hub, there needs to be a ALL_ZONE_STEREO_OFF option. Or, call ALL_ZONE_STEREO_OFF internally before setting the new sound mode. 

Can help with testing, have: X1000, X2100 and X3400

Thank you again !

**Comment by andrewsayre** [comment]
Hmm...  There is code to turn it off before switching to another sound mode: https://github.com/scarface-4711/denonavr/blob/master/denonavr/denonavr.py#L1453-L1455

Is it sticking in all circumstances?  I could see the mode not being reported back if the device is power-cycled and the library doesn't know it's active anymore.

**Comment by DanskerUS** [comment]
Andrew,

Thank you very much for your reply!

Did get X3400H added to HA along with X1000 and X2100W. Did some testing on all of them.

First, I did test for the point you make about HA and Denon device getting out of sync. In most of my use cases, a mix of voice, HA and OEM IR remotes are used. Yes, turning the Denon off/on using the OEM IR remote results in the Denon's sound mode reported as "sound mode" or blank. I can set it from HA, and it works. The on/off, volume and source is being synced/pooled, but apparently sound mode is not.

For all three, a main zone Off/On always clears ALL_ZONE_STEREO mode.

There is something else going on:

X3400H, X2100W and X1000: When ALL_ZONE_STEREO is on, the Off command to either main OR zone2, turns both off. If so, the ALL_ZONE_STEREO could/should be set to Off before the main or zone2 Off is sent; that way, basic on/off works the same for all sound modes.

Also:

On the X3400H and X2100W: Once the ALL_ZONE_STEREO is ON (by either IR or HA), then HA fails to set any other sound mode, Only way to clear ALL_ZONE_STEREO on mode, it to power cycle. The Denon OEM IR remote can turn the sound mode off.

On the X1000: sounds modes can be set as expected (code to turn off ALL_ZONE_STEREO first works!).

And:

Source selection is a bit different on the three Denons if ALL_ZONE_STEREO is on, as follows:

X1000: main zone can be set on anything, zone2 two on "Source" (same as main zone), or RCA audio inputs.

X2100W  and X3400H: main zone and zone 2 track, change source on either and the other change to same.

This could be a Denon firmware limitation/bug.

Re X3400H: It can convert digital (HDMI source) audio to analog and send it out zone2 without all_stereo_on being on, However, still need all_stereo_on mode whenever the main zone and zone2 are within earshot of each other to avoid echo caused by different (audio processing) time delays between the two zones.

Separately, occasionally I am getting "Not able to match sound mode: 'PLIIz Height', returning raw sound mode." in the logs; likely from the X2100W.

All Denons have current firmware, HA 89.2 on PI 3+ 

If you made it all the way here, thank you very much for taking a look!

**Comment by DanskerUS** [comment]
Closed in error, sorry.

**Comment by DanskerUS** [comment]
A bit more testing:

You may already know: 

X3400H and X2100W: if main zone is on, zone2 off, then set main_zone to all_stereo_on, that turns zone2 on.

X1000: zone2 does not turn on. 

Not sure you can do much about that.

After all this, I think the most important part is: being able to turn all_stereo_on mode off for X2100W and X3400H (and likely others as well).

Also, if I unplug the receiver while on. HA does not fully recovers sync (and soundmode stays blank). A HA reboot is required to resync. I suggest a full resync after a power on would clear this up.

Let me know I if can help in some way.

**Comment by ol-iver** [comment]
Please test again once this is included to home-assistant https://github.com/home-assistant/home-assistant/pull/30421

**Comment by DanskerUS** [comment]
Thank you for your efforts, will test and report back.
