### ISSUE TITLE
Sound mode - Atmos

### ISSUE THREAD

**Issue by imbaimbaimba** [ol-iver/denonavr#79]
Hi,
Keep getting this error on atmos:
[DenonAVR] Not able to match sound mode: 'Dolby Atmos', returning raw sound mode.

According to the instructions on HA: https://www.home-assistant.io/components/media_player.denonavr/ , I should post an issue here if I saw this, so here goes :)

**Comment by starkillerOG** [comment]
@imbaimbaimba thanks for reporting!
I included the sound mode 'Dolby Atmos' in this PR: https://github.com/scarface-4711/denonavr/pull/81

**Comment by starkillerOG** [comment]
@scarface-4711 This issue can be closed, since it is solved by PR #81 that just got merged.

**Comment by ol-iver** [comment]
Great 😊
