### ISSUE TITLE
Unable to power on AVR-1912

### ISSUE THREAD

**Issue by bouyssic** [ol-iver/denonavr#87]
Hello Team,

I need your help on an issue that I have with a Denon AVR-1912.

All is working wonderfully except the power_on. I thought it was an issue from the HA interface but browsing the GIT I kinda understood how to interact with it directly from python. See for yourself : 
``# python
Python 3.7.3 (default, May  8 2019, 05:28:42) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import denonavr
>>> d = denovar.DenonAVR("192.168.1.61")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'denovar' is not defined
>>> d = denonavr.DenonAVR("192.168.1.61")
Receiver name could not be determined. Using standard name: Denon AVR.
>>> d.power
'ON'
>>> d.power_off()
True
>>> d.power
'STANDBY'
>>> d.power_on()
Connection error: power on command not sent.
False
>>> 
``

Can you help me debug this see if I can get it to work?

Thanks
Chris

**Comment by bouyssic** [comment]
Oh by the way. I tried using "denon" lib to no avail either. Maybe an option on my AVR that I have to enable? (I do have "Network Standby" setting to "ON")

**Comment by aleksanderpsuj** [comment]
On my denon i have something like IP Control in my web setup menu.
If you have something like that turn it on
![dendfsa](https://user-images.githubusercontent.com/19539245/58568628-e39ae400-8234-11e9-9bf9-5ef28bfcea75.PNG)
