### ISSUE TITLE
unmatched sound mode

### ISSUE THREAD

**Issue by almostserious** [ol-iver/denonavr#88]
Not able to match sound mode: 'Dolby Digital +   + Neural:X', returning raw sound mode.

**Comment by ol-iver** [comment]
Which version are you using?
It should be included since this pull request: https://github.com/scarface-4711/denonavr/commit/38d6f54e74eb4a553725d818ce18d8d0d944ebfd#diff-18d32fba6089c732c810ffa526db114c
