### ISSUE TITLE
Source select FM / Tuner not working on Marantz NR1603

### ISSUE THREAD

**Issue by willemlj** [ol-iver/denonavr#91]
Selecting any source other than FM/Tuner works without any problem. The custom name for the source is displayed as well.

In the source list the (analogue) radio is displayed as 'FM'. It seems this is also send to the receiver as the source name. This does not work. The expected source name is 'TUNER'.

A fix is to add a source mapping like this:

SOURCE_MAPPING = {"TV AUDIO": "TV", "iPod/USB": "USB/IPOD", "Bluetooth": "BT",
                  "Blu-ray": "BD", "CBL/SAT": "SAT/CBL", "NETWORK": "NET",
                  "Media Player": "MPLAY", "AUX": "AUX1", "Tuner": "TUNER", "FM": "TUNER" }

**Comment by ol-iver** [comment]
Fixed in [version 0.7.10](https://github.com/scarface-4711/denonavr/releases/tag/0.7.10)

**Comment by willemlj** [comment]
Thanks for the fix and the great work on this HASS extension!

**Comment by ol-iver** [comment]
you are welcome :-)
