### ISSUE TITLE
Q: Marantz - is it possible to change hdmi output settings ?

### ISSUE THREAD

**Issue by gibman** [ol-iver/denonavr#93]
hi.

I'm running home assistant and was looking into my options in terms being able to change the hdmi output from monitor1 to monitor2 and vice versa.

The settings are found in the AVR menu using:
setup
video
output settings: monitor 1 .. monitor 2 etc.

Ive downloaded the android AVR remote software and this is able to achieve this over the network, although manually :(

**Comment by gibman** [comment]
found the API here .. and looking at page 10 I see some details regarding changing output.

Typing this into a browser seems to work :)

http://192.168.1.x:8080/goform/formiPhoneAppDirect.xml?VSMONIAUTO
http://192.168.1.x:8080/goform/formiPhoneAppDirect.xml?VSMONI1
http://192.168.1.x:8080/goform/formiPhoneAppDirect.xml?VSMONI2

Would it be hard to implement support for this ?

**Comment by gibman** [comment]
for good measure I analyzed a a wireshark dump and found out how to query for the current monitor out settings...

just make a http POST to :
http://192.168.1.x:8080/goform/AppCommand0300.xml
along with a body like this:

`
%0A%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%0A%3Ctx%3E%0A%20%3Ccmd%20id%3D%223%22%3E%0A%20%20%3Cname%3EGetOutputSettings%3C%2Fname%3E%0A%20%20%3Clist%3E%0A%20%20%20%3Cparam%20name%3D%22videoout%22%3E%3C%2Fparam%3E%0A%20%20%20%3Cparam%20name%3D%22videomode%22%3E%3C%2Fparam%3E%0A%20%20%20%3Cparam%20name%3D%22ipscaler%22%3E%3C%2Fparam%3E%0A%20%20%20%3Cparam%20name%3D%22resanalog%22%3E%3C%2Fparam%3E%0A%20%20%20%3Cparam%20name%3D%22reshdmi%22%3E%3C%2Fparam%3E%0A%20%20%20%3Cparam%20name%3D%22progmode%22%3E%3C%2Fparam%3E%0A%20%20%20%3Cparam%20name%3D%22aspect%22%3E%3C%2Fparam%3E%0A%20%20%3C%2Flist%3E%0A%20%3C%2Fcmd%3E%0A%3C%2Ftx%3E
`


in my case I was looking for the "videoout" param name.

response would look like this:

`%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%20%3F%3E%0A%3Crx%3E%0A%3Ccmd%3E%0A%3Cname%3EGetOutputSettings%3C%2Fname%3E%0A%3Clist%3E%0A%3Cparamname%3D%22videoout%22control%3D%222%22%3E1%3C%2Fparam%3E%0A%3Cparamname%3D%22videomode%22control%3D%222%22%3E1%3C%2Fparam%3E%0A%3Cparamname%3D%22ipscaler%22control%3D%222%22%3E0%3C%2Fparam%3E%0A%3Cparamname%3D%22resanalog%22control%3D%221%22%3E1%3C%2Fparam%3E%0A%3Cparamname%3D%22reshdmi%22control%3D%221%22%3E1%3C%2Fparam%3E%0A%3Cparamname%3D%22progmode%22control%3D%221%22%3E1%3C%2Fparam%3E%0A%3Cparamname%3D%22aspect%22control%3D%221%22%3E1%3C%2Fparam%3E%0A%3C%2Flist%3E%0A%3C%2Fcmd%3E%0A%3C%2Frx%3E`


videoout value 1 = monitor1
videoout value 2 = monitor2
videoout value 3 = monitor auto

it works on my marantz sr-6012

sorry for the encoded xml markup.. no clue on how to post XML on github forum. Apparently too big a task for me.

Just decode it back to xml:
https://meyerweb.com/eric/tools/dencoder/

**Comment by skynetforcats** [comment]
If you're using home assistant and/or node red there is also telnet. I believe your model has that feature. I found a pretty extensive Marantz command list from 2013.
