### ISSUE TITLE
Non matching sound mode 'Dolby Audio - DD + DSur'

### ISSUE THREAD

**Issue by justinbyoung** [ol-iver/denonavr#99]
I am getting the following error in my HA logs.

Not able to match sound mode: 'Dolby Audio - DD + DSur', returning raw sound mode.

Could this sound mode please be added to the matching dictionary. I am running a Marantz SR6013. 

Thanks

**Comment by justinbyoung** [comment]
Is there a way for me to do this manually for myself?

**Comment by justinbyoung** [comment]
Another one:

Not able to match sound mode: 'DTS-HD + Neural:X', returning raw sound mode.

**Comment by starkillerOG** [comment]
@justinbyoung I just made a PR to include the two sound modes that were missing.
As soon as that PR gets merged and HomeAssistant is updated it will solve it for you.

For now you could clone this repositry and add in the lines I changed in the PR and then use it as a custom component untill this gets merged. (Not sure how comfortable you are with development of HASS)

**Comment by justinbyoung** [comment]
Excellent, thanks. If I find time I will try installing as a custom component to test.

**Comment by ol-iver** [comment]
Added the changes to the library and home-assistant https://github.com/home-assistant/home-assistant/pull/30421
